### ISSUE TITLE
Create an architecture document

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#1]
We need to create an `ARCHITECTURE.md` that covers the overall system.

This document could, if necessary, reference architecture documents found in each components  repository. These would essentially document just themselves. The intent is to *define once and reference as many times as needed*.

For example, the `ARCHITECTURE.md` created in this repository may say something like:

> For further details on the Kata shim implementation, refer to [the shim architecture document](https://github.com/kata-containers/shim/blob/master/ARCHITECTURE.md)

# Component repositories

The individual `README.md` files in each code repository must contain a reference to this central architecture document.

If a component repository has a separate `ARCHITECTURE.md` this:

- Must be referenced in the components `README.md`.
- Must itself reference the central `ARCHITECTURE.md` document.

For an example of what we should be aiming for, see the Clear Containers architecture document:

- https://github.com/clearcontainers/runtime/blob/master/docs/architecture/architecture.md

# Diagrams

All diagrams must:

- Be stored along with their corresponding "source" files (for example, if a `.png` file is referenced, the `.svg` file that was used to generate the `.png` must also be stored to allow the diagrams to be updated by all.
- Use freely available open formats for their sources.

**Comment by grahamwhaley** [comment]
@jodh-intel - is this Issue satisfied by https://github.com/kata-containers/documentation/blob/master/architecture.md ?

**Comment by jodh-intel** [comment]
Technically, no, as we're missing the sources for the PNG files.

@egernst - could you rustle up the sources for the PNG files here: https://github.com/kata-containers/documentation/tree/master/arch-images ?
