### ISSUE TITLE
Opensuse Kata-containers repo not available

### ISSUE THREAD

**Issue by vizdrag561** [kata-containers/documentation#122]
Hi team,
Centos7Minimal+Docker. I try to install kata with your docs:
https://github.com/kata-containers/documentation/blob/master/install/centos-installation-guide.md
When i want to add a new opensuse repo, i get an error:
`# sudo -E VERSION_ID=$VERSION_ID yum-config-manager --add-repo "http://download.opensuse.org/repositories/home:/katacontainers:/release/CentOS_${VERSION_ID}/home:katacontainers:release.repo"
Loaded plugins: fastestmirror
adding repo from: http://download.opensuse.org/repositories/home:/katacontainers:/release/CentOS_/home:katacontainers:release.repo
grabbing file http://download.opensuse.org/repositories/home:/katacontainers:/release/CentOS_/home:katacontainers:release.repo to /etc/yum.repos.d/home:katacontainers:release.repo
Could not fetch/save url http://download.opensuse.org/repositories/home:/katacontainers:/release/CentOS_/home:katacontainers:release.repo to file /etc/yum.repos.d/home:katacontainers:release.repo: [Errno 14] HTTP Error 404 - Not Found`

And really, repo answer is: Resource is no longer available!

Wait your comments, thx

**Comment by jodh-intel** [comment]
Hi @vizdrag561 - thanks for reporting.

I've just double-checked the centos install instructions and they work fine [*]. I think you may have missed out the important line before (which sets `VERSION_ID`):

```
$ source /etc/os-release
```

Could source that file and confirm it works for you?

----
[*] - If you installing on a non-critical development or test system, you could do what I did and "execute" the installation document to ensure you're running exactly what is specified in the install doc:

```
$ go get -d github.com/kata-containers/documentation
$ go get -d github.com/kata-containers/tests
$ cd $GOPATH/src/github.com/kata-containers/documentation
$ ../tests/.ci/kata-doc-to-script.sh install/centos-installation-guide.md ./centos.sh
$ script -fec 'bash ./centos.sh'
```

**WARNING:** This is **not** a recommended approach and we would **strongly** encourage you to review the script before running it as it runs commands as `root`, may make your machine explode, may eat your cat, you get to keep the pieces, etc, etc... :smile:

**Comment by jodh-intel** [comment]
Hi @vizdrag561 - great! Have fun :smile:
Closing as resolved.
