### ISSUE TITLE
Add directions for public clouds to Install Guide

### ISSUE THREAD

**Issue by annabellebertooch** [kata-containers/documentation#130]
The current Install Guide mostly assumes running on your own cloud and while some of the directions transfer over, it would be good to have the cloud-specific differences noted in the Install Guide (maybe in a new section on the Install Guide so it doesn't get unruly?) so people can get up and running on Azure, GCP, etc. 

Cc'ing @jessfraz @jon @tallclair

**Comment by jon** [comment]
I can pick this up for GCE by pulling apart the one-shot from https://github.com/jon/kubeadm-single-node-cluster/tree/kata into more general instructions.

**Comment by mnaser** [comment]
I'll pick this up for vexxhost

**Comment by jodh-intel** [comment]
Thank's @jon and @mnaser!

**Comment by jodh-intel** [comment]
I've created #155 specifically for GCE.

**Comment by scooley** [comment]
I'm picking this up for Azure.

**Comment by jodh-intel** [comment]
Thanks @scooley - feel free to raise a new issue for that and add a comment on it referencing this one.
