### ISSUE TITLE
Developer guide: Add instructions how to build qemu

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/documentation#133]
Add a section describing how to build qemu compatible for kata.

**Comment by chavafg** [comment]
@jcvenegas any update on this? Thanks

**Comment by jcvenegas** [comment]
Yeah, we  can point to the static build qemu script.

**Comment by egernst** [comment]
I think this is still an open issue -- the developer guide is currently wrong, since it references the QEMU repo in Kata-Containers organization, which is no longer utilized.

**Comment by jodh-intel** [comment]
Need to forward port to 2.0.
