### ISSUE TITLE
Dev-guide: Make "Installing guest kernel images" steps arch-sensitive 

### ISSUE THREAD

**Issue by nitkon** [kata-containers/documentation#140]
The steps mentioned in the Dev-guide to install guest kernel images are x86 specific. We need to pull config files and install guest kernel images depending on the host arch. 

Example: 
if [ $kernel_arch == ppc64le ] ; then curl -L https://raw.githubusercontent.com/kata-containers/packaging/master/kernel/configs/ppc64le_kata_kvm_4.14.x -o .config; else curl -L https://raw.githubusercontent.com/kata-containers/packaging/master/kernel/configs/x86_kata_kvm_4.14.x -o .config;fi

**Comment by grahamwhaley** [comment]
if we used some form of `${arch}_kata_kvm_{kernel_version}` type string, then that might scale nicely across future arch and kernel version additions.
The kernel `{arch}` value is sadly probably different from the apt type arch naming scheme we were discussing earlier though - maybe that one really can use `$(uname -m}` ?

**Comment by nitkon** [comment]
@grahamwhaley :  @jodh-intel : There are other issues as well. For example:

1.$ make ARCH=${kernel_arch} -j$(nproc)
$kernel_arch on ppc64le would be "ppc64le",  however there is no such directory. We need 

``` make ARCH=powerpc -j$(nproc)```

2. $ sudo install -o root -g root -m 0755 -D "$(realpath arch/${kernel_arch}/boot/bzImage)" "${kata_vmlinuz}"
There is no "boot/bzImage" in case of ppc64le, we need to 

 ```$ sudo install -o root -g root -m 0755 -D "$(realpath ./vmlinux)" "${kata_vmlinuz}"```

Will we need an if-then-else in such a case?

**Comment by nitkon** [comment]
@grahamwhaley : 
1. The {kernel_version} comes from the config file itself. 
2. We will need 3 config files arm64.. , x86... , ppc64le...  Today I guess, arm and x86 use the same config file.

**Comment by Pennyzct** [comment]
We were considering the same issues and preparing the config file😊

**Comment by Weichen81** [comment]
@nitkon In actually, arm64 has another config file, I will create an issue and PR later to upload the config file for arm64 ; )

**Comment by nitkon** [comment]
@jodh-intel : Given that the kata-arch script  returns ``` x86_64 ``` as arch on intel, should we rename the kernel config file to ```x86_64_kata_kvm_4.14.x``` ? Or do a cut on the returned value for ```x86```? 

Reference: https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#install-guest-kernel-images

**Comment by jodh-intel** [comment]
@nitkon - yes, I think we should rename it to have a `x86_64` prefix.
