### ISSUE TITLE
Document preferred diagramming tools and flows

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/documentation#165]
In the past we have tried to stick to diagramming tools that are open and allow easy editing of existing diagrams (that is, they are not just raw png, but have some other source such as text or svg that the png files are then produced from).
We should document this to:
- keep some uniformity
- help others get a quickstart without having to research tooling
- help others update existing diagrams

For instance, we have a bunch of nice UML generation [in the arch diagrams](https://github.com/kata-containers/documentation/tree/master/arch-images), but I don't think we note how to process them.

@jcvenegas @egernst - if you drop any details you have here, I'll add a doc.

**Comment by jodh-intel** [comment]
Thanks for raising. No new doc required though - please just update:

- https://github.com/kata-containers/documentation/blob/master/Documentation-Requirements.md
