### ISSUE TITLE
document oldest docker version supported

### ISSUE THREAD

**Issue by egernst** [kata-containers/documentation#169]
Version 1.13 docker does not work.  We should document the minimal version supported.

**Comment by jodh-intel** [comment]
Yes - the oldest Docker version we claim to work with is 1.12.1 which is documented in the versions database:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml#L137.

Some users have been having success with Docker 1.11 though:

- https://github.com/kata-containers/runtime/pull/334

I'd recommend updating https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#requirements-to-build-individual-components to point the users at the very human-readable YAML file to avoid hard-coding the version number in another location.

**Comment by jodh-intel** [comment]
Given you're saying 1.13 doesn't work, it looks like we'll have to investigate why 1.11 and 1.12 work (or used to), but 1.13 does not.

**Comment by egernst** [comment]
ACK - I'll try to get more details from the person who had the issue here at the hackathon.  I didn't see where the limitation/last version was defined - thanks for pointing it out.
