### ISSUE TITLE
Remove ramdisk limitation from limitations.md

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#170]
Once https://github.com/kata-containers/runtime/pull/412 lands, we can remove the docker ramdisk limitation:

- https://github.com/kata-containers/documentation/blob/master/Limitations.md#docker-ramdisk-not-supported

**Comment by jodh-intel** [comment]
This is a good first issue as it's simply removing some text from a document ;)

**Comment by amshinde** [comment]
@jodh-intel Lets gate this on a test being added first to check if running using a RAMDISK is supported. I am not sure if we need to add some more logic in the runtime for this besides just supporting the flag.

**Comment by jodh-intel** [comment]
Agreed - this should be blocked on https://github.com/kata-containers/tests/issues/429.
