### ISSUE TITLE
logging: journald may rate limit our logs with full debug on

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/documentation#181]
Enabling full debug and running multiple containers sequentially or concurrently can cause `journald` to rate limit (and therefore drop) some of our system log messages.
Document this fact, how to identify if it is happening, and what the solutions/workarounds are.

Related to https://github.com/kata-containers/runtime/issues/450

Fixes include:
 - upping or turning off the `journald` rate limits (I need to see if we can do this on a per-unit basis - I suspect so)
 - making use of the file based json logs that we also capture (at the bequest of docker), which are complete, as they do not get filtered through the system log. This can involve a 'shell script indirector' for the runtime, to ensure we capture the logs before docker deletes them again (on `docker rm`).

**Comment by grahamwhaley** [comment]
Related thread for more background info: https://github.com/openshift/openshift-ansible/pull/3753

**Comment by jodh-intel** [comment]
This info should go in the dev guide as a minimum I think.

**Comment by grahamwhaley** [comment]
@jodh-intel you mean how to identify and then configure away the problem, or the openshift link?
I'm writing the generics into the dev guide right now. Will PR that rsn.

**Comment by jodh-intel** [comment]
I mean removing the systemd rate-limit.
