### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#184]
The installation guides are referring to a no-longer valid section name in the developer guide.

**Comment by nitkon** [comment]
@jodh-intel : So IIUC,  CentOS, Fedora, Red Hat, Ubuntu installation guides are not pointing to the right `Kubernetes` link when deciding which container manager to use.  The correct link being: `https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#install-kubernetes`

I can fix this, if this is what is to be done.

**Comment by jodh-intel** [comment]
Hi @nitkon - thanks for offering but I'd raised this for @scooley on #183.

**Comment by jodh-intel** [comment]
I wish we could find a way to allow both users to self-assign issues and allow us to assign to new contributors :)

**Comment by nitkon** [comment]
@jodh-intel : Ahh okay, no problem.

**Comment by jodh-intel** [comment]
It's rather annoying actually because those links changed but our URL checker didn't notice:

https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L363

I'm really not sure what we can do about that aside from downloading the document and `grep`-ing for the anchor name HTML.

**Comment by grahamwhaley** [comment]
@jodh-intel - as for enabling external contributors, sadly it looks like you should not hold your breath.... https://github.com/isaacs/github/issues/100 :-(

**Comment by jodh-intel** [comment]
Wow - 5 years....
