### ISSUE TITLE
Devs: console: the console sock has moved from sbs to vm dir

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/documentation#202]
It looks like the `console.sock` used to gain access to a console on the VM no longer lives in `sbs`, but is in `vm`. Fix the docs.

**Comment by jodh-intel** [comment]
Did that work?

**Comment by grahamwhaley** [comment]
It ..... did! `CTRL-q` quits the socat. I don't know if that is socat or QMP or ??? - but it works :-)

**Comment by devimc** [comment]
the trick is `escape`

```
socat stdin,raw,echo=0,escape=0x11 ...
```
