### ISSUE TITLE
A problem about yum when install the kata

### ISSUE THREAD

**Issue by yuzhongwei** [kata-containers/documentation#206]
Just install the Kata step by step with the documentation,but when  operate the command 'sudo -E yum -y install kata-runtime kata-proxy kata-shim' ， the centos is always changing the yum mirrors ，and can‘t
install.

**Comment by jodh-intel** [comment]
Hi @yuzhongwei - thanks for raising!

Couldy you paste the messages / errors you are seeing?

I suspect this might be a problem with OBS we have been suffering from recently.

/cc @chavafg.

**Comment by chavafg** [comment]
Yes, I think this could be related to the OBS services being too slow. @jcvenegas do you know if somehow we can report these issues?

**Comment by jodh-intel** [comment]
Potentially related: https://github.com/kata-containers/kata-containers/issues/26.

**Comment by adrianschroeter** [comment]
the provo-mirror should be fixed.

**Comment by jodh-intel** [comment]
Hi @adrianschroeter - sorry - not sure I follow completely. Is this something you can look at for us?

**Comment by adrianschroeter** [comment]
I read "Timeout on http://provo-mirror.opensuse.org/" ... this particular mirror was down, but should work fine meanwhile. Speak up if not.

**Comment by yuzhongwei** [comment]
today I try again , it can work
