### ISSUE TITLE
stable: consider forking documentation repository

### ISSUE THREAD

**Issue by egernst** [kata-containers/documentation#246]
see https://github.com/kata-containers/documentation/pull/238#discussion_r216558185

**Comment by amshinde** [comment]
@jcvenegas We never really got to this. Considering that we maintain stable branches for other repos, we should do it for documentation repo as well. 
Do you see any issues with it?

cc @jodh-intel

**Comment by mvincerx** [comment]
I'm not quite clear on what you're asking. If I  understand your question: I support keeping a stable branch for documentation and using a `fork and clone` model. 

IMHO: The contributing guide could be condensed a lot.  I believe that the example PR and the explanation of how to fork and submit a PR could  be replaced with links to GitHub or Atlassian instructions.
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md

**Comment by jcvenegas** [comment]
+1 on branch the documentation as well,  @mvincerx  that would happen is that after create an stable branch for kata in documentation repository a new branch will be created as well `stable-X.Y` this will keep the relevant documentation valid for stable release, this will help to keep sync/valid the  documentation for users that use an specific stable branch.

**Comment by jodh-intel** [comment]
@mvincerx - yes, that's what we're suggesting on this issue. We already create stable branches for the main components (runtime, agent, shim, proxy), but also create stable branches for the tests repository to ensure it doesn't get bloated with having to support "n" backlevel releases. So, it seems odd that we don't do the same for the docs repo as it would allow each stable docs branch to only document that version of Kata without extra "bloat". That way, we never get into the horrors of having to maintain documentation that states such horrors as:

> If you're running a version of Kata older than a.b.c (with the exception of version a.d.c), or a version newer than e.f.g), run the command below...
>
> If instead you are using version h.i.j with the config option foo (which was deprecated in version o.m.g and is planned for removal in version O.M.G) set to "wibble", "moo" or "halp", give up now.
