### ISSUE TITLE
Document GPU passthrough with Kata

### ISSUE THREAD

**Issue by amshinde** [kata-containers/documentation#250]
Now that all PRs related to GPU passthrough have been merged, we should document Graphics passthrough (GVT-g and GVT-d) with Kata.

**Comment by amshinde** [comment]
cc @xindazhao

**Comment by nfrush** [comment]
@amshinde Is there going to be documentation on this? Would love to test it out as a feature.

**Comment by amshinde** [comment]
@nfrush Here is the documentation for Intel GPUs with Kata:
https://github.com/kata-containers/documentation/blob/master/use-cases/GPU-passthrough-and-Kata.md
