### ISSUE TITLE
Limitations: document the current status of selinux support

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/documentation#252]
Selinux support is not presently available under Kata, as seen at https://github.com/kata-containers/runtime/issues/784.
At a minimum, document that in the limitations doc. It is probably wise to also open a specific issue, probably on the agent repo?, that selinux is not supported.
We need to start with that age-old discussion of where is one expecting it to be applied - on the host or inside the VM?

**Comment by jodh-intel** [comment]
:chestnut: :chestnut: :chestnut: (:arrow_left: speaking of age-old... those are *chestnuts*! :smile:)
