### ISSUE TITLE
any plan to support arm64?

### ISSUE THREAD

**Issue by bilang** [kata-containers/documentation#254]
ubuntu on arm64 platform, following the installation guide

$ sudo -E apt-get -y install kata-runtime kata-proxy kata-shim
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package kata-runtime
E: Unable to locate package kata-proxy
E: Unable to locate package kata-shim

**Comment by jodh-intel** [comment]
Hi @bilang - thanks for raising!

For OBS, unfortunately we only currently provide x86_64 binaries. See:

- https://github.com/kata-containers/packaging/issues/118
- https://github.com/kata-containers/packaging/issues/195

However, we do provide an arm64 snap package for Ubuntu [*]:

- https://snapcraft.io/kata-containers

---
[*] - no ppc64le snaps as yet - https://github.com/kata-containers/packaging/issues/97

/cc @nitkon, @Pennyzct, @Weichen81,

**Comment by Weichen81** [comment]
Hi @bilang, we are chasing the x86_64 ; )

**Comment by jodh-intel** [comment]
:racing_car: ...

**Comment by marcov** [comment]
Hi, OBS can build binaries for aarch64, ppc64le and others if instructed properly :)

I think that as part of the transition to an official OBS repo that I announced on kata-dev, it would make sense to start building and supporting also non x86 architectures.

This involves some updates to the spec files and also find a way to correctly distribute the rootfs/initrd images based on the architecture. 

I'm all in starting to have a look at this, as I really want to have kata officially available on SUSE :)

WDYT?

/cc @jcvenegas

**Comment by jcvenegas** [comment]
@marcov  agree, we had an starting for non x_86_64 from @nitkon  but agree this is something we have to provide.

**Comment by amshinde** [comment]
@nitkon @jcvenegas @Pennyzct Is this still relevant? Is there any ongoing work for this?
