### ISSUE TITLE
build: note `yq` may now be required to build runtime

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/documentation#262]
Now we do a min version check using `yq` to extract the info from the `versions.yaml` file, note on the docs at https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#requirements-to-build-individual-components that `yq` is a required installed component to build (the runtime at least).

**Comment by GabyCT** [comment]
Closing this issue as if `yq` does not exist it will be installed as a pre-requisite
