### ISSUE TITLE
Add snappy installation instructions

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#274]
Since we provide Kata as a snap...

- https://snapcraft.io/kata-containers

... we need some instructions explaining how to install on a system running the snapd package manager.

**Comment by devimc** [comment]
@marcov @jodh-intel 

https://github.com/kata-containers/packaging/blob/master/snap/README.md is for developers while https://github.com/kata-containers/documentation/pull/318 is for users

what do you think?

**Comment by jodh-intel** [comment]
Sounds good - thanks @devimc! ;)
