### ISSUE TITLE
kata-manager docs don't work as documented

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#275]
Following the doc below fails to produce a working system:

- https://github.com/kata-containers/documentation/blob/master/install/installing-with-kata-manager.md

**Comment by jodh-intel** [comment]
@marcov - do you wanna take a look at this one? Let me know either way.

**Comment by marcov** [comment]
@jodh-intel: sure. Is the problem the extra `$` on line wrap?

**Comment by jodh-intel** [comment]
Yes, we need to remove the extra `$ `, but I'd also remove the backslashes as all commands are on a single line (let gfm handle the scroll bars, etc).

But the bigger problem is that running the curl command -- even removing the `$` cruft -- just doesn't work so we either need to rework the instructions in this doc, or improve https://github.com/kata-containers/tests/blob/master/cmd/kata-manager/kata-manager.sh so it can work as documented.

**Comment by jodh-intel** [comment]
... And finally, we should try to get this install method hooked into the CI so that it gets tested of course ;)

**Comment by marcov** [comment]
What distro are you using? They both works for me on {suse,ubuntu}. 

np removing backslashes, I didn't know about auto wrapping in github :)

**Comment by marcov** [comment]
ohh, now I see that the problem :)
Yes, I guess at least go and git have to be listed as prereq. 

I'd have a preference to have the missing steps implemented in `kata-manager`, since we are selling it as an "automated" installation method. wdyt?

**Comment by jodh-intel** [comment]
+1. It could install git and golang maybe.

**Comment by jodh-intel** [comment]
... we might also want to consider adding a `--dry-run` / `-n` option for `kata-manager` so users can see what would be installed. Alternatively, the default could be to use `dnf -y` / `apt -y`, but if `--prompt` or `--interactive` were specified to `kata-manager` it would drop the `-y` and prompt the user if they want to install the packages.

**Comment by grahamwhaley** [comment]
You might want some warning/caveats about the golang install - the distro version may not be new enough, and where would we then install the upstream tarball - in the 'normal' `/usr/local/go` - seems a little presumptuous unless we forwarn the end user.
`git` version from distro should be fine though :-)

**Comment by jodh-intel** [comment]
I just checked and I already added a `-n` option to `kata-manager` ;)

Also, the golang version issue isn't actually a problem since:

- We would only need "a version" of golang to run the `kata-manager` script - it doesn't build any go code so doesn't have to be pinned to the golang version in https://github.com/kata-containers/runtime/blob/master/versions.yaml or newer.

- In fact the script only needs `go` to find out what `GOPATH` is - and it then `git clone`'s into a subdir of that.

**Comment by marcov** [comment]
I'd prefer to let the user install git/golang by himself.  Any recent distro should have it packaged. kata-manager could just check if the executable is installed, and if not, gracefully notify the user.

**Comment by jodh-intel** [comment]
I take the point, but If we want to automate the testing of this doc, we either need `kata-manager` to install those packages, or we need to create a bunch of `installing-with-kata-manager-on-${distro}.md` docs, one per distro where we specify the bash code block suitable for that distro to install the tools.

As you say, we want kata-manager to be the simplest install method, but non-developers may not have git installed and are highly unlikely to have golang installed I suspect.

**Comment by marcov** [comment]
What do you think about going with this solution?

- given that {go,git} are only used to pull the tests repository, we replace that with a `curl -fsSL https://github.com/kata-containers/documentation/archive/master.zip`
(or is wget better?)

- IFF `kata-doc-to-script.sh` is not found, it can be run with `bash -c "$(curl -fsSL https://raw.githubusercontent.com/.../kata-doc-to-script.sh) "`

**Comment by jodh-intel** [comment]
Hi @marcov - the `master.zip` is a clever idea but `zip(1)` isn't installed by default on some distros. However, we could consider:

- https://github.com/kata-containers/documentation/archive/master.tar.gz

... since `tar(1)` and `gzip(1)` seem pretty safe :)

We tend to always specify `curl` for CLI downloads [1] as it seems to be more actively maintained, etc. However as long as only one of them is specified in a ` ```bash ` block, we could document both I guess.

wdyt @grahamwhaley?

---
[1] - That in itself might be problematic as I'm not sure `curl` is always installed by default, but `wget` seems to be.

**Comment by grahamwhaley** [comment]
`curl` is preferable, but you could always code up an `if/else` check with `command` to try `curl`, and if you don't find it try `wget` :-), and then bomb if you have neither.
