### ISSUE TITLE
Lost all of my old images if I follow the docker step

### ISSUE THREAD

**Issue by allenhaozi** [kata-containers/documentation#300]
$ dir=/etc/systemd/system/docker.service.d
$ file="$dir/kata-containers.conf"
$ sudo mkdir -p "$dir"
$ sudo test -e "$file" || echo -e "[Service]\nType=simple\nExecStart=\nExecStart=/usr/bin/dockerd -D --default-runtime runc" | sudo tee "$file"
$ sudo grep -q "kata-runtime=" $file || sudo sed -i 's!^\(ExecStart=[^$].*$\)!\1 --add-runtime kata-runtime=/usr/local/bin/kata-runtime!g' "$file"
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker

this will make my existed image lost, because I set custom graph dir

**Comment by jodh-intel** [comment]
Hi @Allenhaozi - I think you are referring to https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#update-docker-configuration?

Unfortunately, running the commands in that guide are "at your own risk":

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#warning
- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#assumptions

However, ideally we would either not modify the docker `ExecStart=`, or we would ensure the existing settings are retained. Were you running `dockerd --storage-driver=...` ?

/cc @grahamwhaley, @chavafg.

**Comment by marcov** [comment]
One improvement is to detect any existing docker service file with:
```
sudo systemctl show -p FragmentPath docker.service
```
This is because unit files could be placed in `/etc/systemd`, `/usr/lib/systemd`, ..., and this should be taken into account to avoid masking out an existing unit file.
