### ISSUE TITLE
Document the supported hardware architectures

### ISSUE THREAD

**Issue by marcov** [kata-containers/documentation#302]
AFAIK there's no information about the supported architectures, or maybe it's just a little bit hidden :)

I would expect to find what we currently support at [Getting Started](https://github.com/kata-containers/documentation#getting-started) section.

**Comment by jodh-intel** [comment]
It's almost documented in https://github.com/kata-containers/runtime#platform-support so maybe we could just put a table in that section? :)

**Comment by marcov** [comment]
Ok, we can add a new table from the link you provided in Getting Started, but make the content a bit easier to interpret.
