### ISSUE TITLE
Add limitations document

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#31]
We need to create an equivalent of the [Clear Containers limitations document](https://github.com/clearcontainers/runtime/blob/master/docs/limitations.md).

Every limitation listed **MUST** be accompanied by a reference to an issue number.

**Comment by jodh-intel** [comment]
An alternative approach would be to raise issues for all limitations and add a `limitation` label. That would allow users to perform a github issue search for all outstanding limitations.

# Pros

- :+1: Simple.
- :+1: Easy to maintain and understand (limitation has obviously been overcome once the issue is closed).

# Cons

- :-1: A github issue report listing limitations cannot be versioned and referred to in a release.
- :-1: Issues are often long and thus take time to understand. However, a doc can provide an "executive summary" of the problem with a link to the gory details in the issue.

My vote is that we create a doc.

wdyt @xu, @bergwolf, @egernst, @grahamwhaley?

**Comment by grahamwhaley** [comment]
Both.
Create the doc with the requirement that each limitation has a PR - but also ensure that each of those PRs has a `limitations` label as well :-)

We might do worse than to bring over the [CC limitations](https://github.com/clearcontainers/runtime/blob/master/docs/limitations.md) doc and go through it one by one and:
- verify the limitation still exists
- see if the related CC Issue will mostly carry over, or if we should create a fresh one

**Comment by jodh-intel** [comment]
I like it! ;)

**Comment by egernst** [comment]
Makes sense to me!

**Comment by egernst** [comment]
Makes sense to me!

**Comment by jodh-intel** [comment]
We now have a limitation label.
