### ISSUE TITLE
 KataContainers fails to install Ubuntu LTS.

### ISSUE THREAD

**Issue by gaby** [kata-containers/documentation#325]
The current ubuntu-installation-guide.md fails in a new Ubuntu Xenial 16.04 Installation.

> root@ubuntu-VirtualBox:/etc/apt# ARCH=$(arch)
root@ubuntu-VirtualBox:/etc/apt# sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/master/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/kata-containers.list"
root@ubuntu-VirtualBox:/etc/apt# curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/master/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -
OK
root@ubuntu-VirtualBox:/etc/apt# sudo -E apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                           
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]                                                      
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                                                             
Ign:5 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_16.04  InRelease                              
Get:6 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_16.04  Release [716 B]
Get:7 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_16.04  Release.gpg [481 B]
Get:8 http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_16.04  Packages [2,113 B]
Fetched 326 kB in 0s (458 kB/s)       
Reading package lists... Done
root@ubuntu-VirtualBox:/etc/apt# sudo -E apt-get -y install kata-runtime kata-proxy kata-shim
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation: 
The following packages have unmet dependencies:
 kata-runtime : Depends: kata-linux-container (>= 4.14.67.20-15) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@ubuntu-VirtualBox:/etc/apt# 

-------------------------------------------------------------------------------------------------------------------------------
The following command gives me no results (Version not found):
> apt install kata-linux-container=4.14.67.20-15

I manage to get it working by using the repository/key from a previous commit in that file:

**Commit # 795400525cc834d90f92c2edc682a50362d57496**

> $ sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/kata-containers.list"
   $ curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add - 

Using the above commands I get this:

>root@ubuntu-VirtualBox:/etc/apt/sources.list.d# sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/kata-containers.list"
root@ubuntu-VirtualBox:/etc/apt/sources.list.d# curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -
OK
root@ubuntu-VirtualBox:/etc/apt/sources.list.d# sudo -E apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                                                                 
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                                                                         
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]                                                                
Ign:5 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  InRelease                                                
Get:6 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  Release [671 B]
Get:7 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  Release.gpg [481 B]
Get:8 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  Packages [2,102 B]
Fetched 326 kB in 0s (463 kB/s)       
Reading package lists... Done
root@ubuntu-VirtualBox:/etc/apt/sources.list.d# sudo -E apt-get -y install kata-runtime kata-proxy kata-shim
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  kata-containers-image kata-ksm-throttler kata-linux-container qemu-lite qemu-vanilla
The following NEW packages will be installed:
  kata-containers-image kata-ksm-throttler kata-linux-container kata-proxy kata-runtime kata-shim qemu-lite qemu-vanilla
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 60.5 MB of archives.
After this operation, 684 MB of additional disk space will be used.
Get:1 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  kata-containers-image 1.4.0-39 [25.9 MB]
Get:2 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  kata-ksm-throttler 1.4.0.git+1212de2-40 [4,058 kB]
Get:3 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  kata-linux-container 4.14.67.18-142 [11.6 MB]
Get:4 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  kata-proxy 1.4.0+git.e1856c2-40 [801 kB]
Get:5 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  kata-shim 1.4.0+git.b02868b-41 [2,542 kB]
Get:6 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  qemu-lite 2.11.0+git.f886228056-56 [5,542 kB]
Get:7 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  qemu-vanilla 2.11.2+git.0982a56a55-53 [5,571 kB]
Get:8 http://download.opensuse.org/repositories/home:/katacontainers:/release/xUbuntu_16.04  kata-runtime 1.4.0+git.21f0059-55 [4,480 kB]
Fetched 60.5 MB in 4s (15.0 MB/s)       
Selecting previously unselected package kata-containers-image.
(Reading database ... 222962 files and directories currently installed.)
Preparing to unpack .../kata-containers-image_1.4.0-39_amd64.deb ...
Unpacking kata-containers-image (1.4.0-39) ...
Selecting previously unselected package kata-ksm-throttler.
Preparing to unpack .../kata-ksm-throttler_1.4.0.git+1212de2-40_amd64.deb ...
Unpacking kata-ksm-throttler (1.4.0.git+1212de2-40) ...
Selecting previously unselected package kata-linux-container.
Preparing to unpack .../kata-linux-container_4.14.67.18-142_amd64.deb ...
Unpacking kata-linux-container (4.14.67.18-142) ...
Selecting previously unselected package kata-proxy.
Preparing to unpack .../kata-proxy_1.4.0+git.e1856c2-40_amd64.deb ...
Unpacking kata-proxy (1.4.0+git.e1856c2-40) ...
Selecting previously unselected package kata-shim.
Preparing to unpack .../kata-shim_1.4.0+git.b02868b-41_amd64.deb ...
Unpacking kata-shim (1.4.0+git.b02868b-41) ...
Selecting previously unselected package qemu-lite.
Preparing to unpack .../qemu-lite_2.11.0+git.f886228056-56_amd64.deb ...
Unpacking qemu-lite (2.11.0+git.f886228056-56) ...
Selecting previously unselected package qemu-vanilla.
Preparing to unpack .../qemu-vanilla_2.11.2+git.0982a56a55-53_amd64.deb ...
Unpacking qemu-vanilla (2.11.2+git.0982a56a55-53) ...
Selecting previously unselected package kata-runtime.
Preparing to unpack .../kata-runtime_1.4.0+git.21f0059-55_amd64.deb ...
Unpacking kata-runtime (1.4.0+git.21f0059-55) ...
Setting up kata-containers-image (1.4.0-39) ...
Setting up kata-ksm-throttler (1.4.0.git+1212de2-40) ...
Setting up kata-linux-container (4.14.67.18-142) ...
Setting up kata-proxy (1.4.0+git.e1856c2-40) ...
Setting up kata-shim (1.4.0+git.b02868b-41) ...
Setting up qemu-lite (2.11.0+git.f886228056-56) ...
Setting up qemu-vanilla (2.11.2+git.0982a56a55-53) ... 

uname -a 

> Linux ubuntu-VirtualBox 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I'm running inside VirtualBox 5.2.22 r126460 (Qt5.6.2).
Any ideas? I also tried with Ubuntu Bionic, same issue.

**Comment by egernst** [comment]
@bergwolf  - is this similar to issue you filed?

https://github.com/kata-containers/packaging/issues/291

**Comment by bergwolf** [comment]
@egernst I found the issue due to the same install failure. Right now the runtime build is fixed by kata-containers/packaging#291, but the guest kernel build is still failing due to OOM e.g., `Out of memory: Kill process 25656 (cc1) score 6 or sacrifice child`

**Comment by egernst** [comment]
I don’t know. @marcov?

**Comment by mrlesmithjr** [comment]
Confirming that I am also seeing this issue with Ubuntu 16.04/18.04.
```bash
TASK [ansible-kata-containers : debian | Installing Kata Containers] ***********
FAILED - RETRYING: debian | Installing Kata Containers (3 retries left).
FAILED - RETRYING: debian | Installing Kata Containers (2 retries left).
FAILED - RETRYING: debian | Installing Kata Containers (1 retries left).
fatal: [node0]: FAILED! => {"attempts": 3, "cache_update_time": 1545892368, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'kata-runtime' 'kata-proxy' 'kata-shim'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n kata-runtime : Depends: kata-linux-container (>= 4.14.67.20-15) but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " kata-runtime : Depends: kata-linux-container (>= 4.14.67.20-15) but it is not going to be installed"]}
```

And when installing on CentOS 7 I get the following:
```bash
TASK [ansible-kata-containers : redhat | Installing Kata Containers] ***********
FAILED - RETRYING: redhat | Installing Kata Containers (3 retries left).
FAILED - RETRYING: redhat | Installing Kata Containers (2 retries left).
FAILED - RETRYING: redhat | Installing Kata Containers (1 retries left).
fatal: [node0]: FAILED! => {"attempts": 3, "changed": false, "msg": "warning: /var/cache/yum/x86_64/7/kata_containers/packages/qemu-vanilla-data-2.11.2+git.0982a56a55-16.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 6063f3ed: NOKEY\n\n\nPublic key for qemu-vanilla-data-2.11.2+git.0982a56a55-16.1.x86_64.rpm is not installed\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: centos.vwtonline.net\n * epel: archive.linux.duke.edu\n * extras: centos.vwtonline.net\n * updates: centos.vwtonline.net\nResolving Dependencies\n--> Running transaction check\n---> Package kata-proxy.x86_64 0:1.5.0~rc2+git.2029708-14.1 will be installed\n--> Processing Dependency: kata-proxy-bin for package: kata-proxy-1.5.0~rc2+git.2029708-14.1.x86_64\n---> Package kata-runtime.x86_64 0:1.5.0~rc2+git.b954eec-19.1 will be installed\n--> Processing Dependency: qemu-vanilla >= 2.11.2+git.0982a56-16 for package: kata-runtime-1.5.0~rc2+git.b954eec-19.1.x86_64\n--> Processing Dependency: qemu-lite >= 2.11.0+git.87517af-16 for package: kata-runtime-1.5.0~rc2+git.b954eec-19.1.x86_64\n--> Processing Dependency: kata-linux-container >= 4.14.67.20-15 for package: kata-runtime-1.5.0~rc2+git.b954eec-19.1.x86_64\n--> Processing Dependency: kata-ksm-throttler >= 1.5.0~rc2+git.d70af5c-15 for package: kata-runtime-1.5.0~rc2+git.b954eec-19.1.x86_64\n--> Processing Dependency: kata-containers-image >= 1.5.0~rc2-13 for package: kata-runtime-1.5.0~rc2+git.b954eec-19.1.x86_64\n---> Package kata-shim.x86_64 0:1.5.0~rc2+git.4138b29-12.1 will be installed\n--> Processing Dependency: kata-shim-bin for package: kata-shim-1.5.0~rc2+git.4138b29-12.1.x86_64\n--> Running transaction check\n---> Package kata-containers-image.x86_64 0:1.5.0~rc2-13.1 will be installed\n---> Package kata-ksm-throttler.x86_64 0:1.5.0~rc2.git+d70af5c-15.1 will be installed\n---> Package kata-linux-container.x86_64 0:4.14.67.20-15.1 will be installed\n---> Package kata-proxy-bin.x86_64 0:1.5.0~rc2+git.2029708-14.1 will be installed\n---> Package kata-shim-bin.x86_64 0:1.5.0~rc2+git.4138b29-12.1 will be installed\n---> Package qemu-lite.x86_64 0:2.11.0+git.87517afd72-16.1 will be installed\n--> Processing Dependency: qemu-lite-data for package: qemu-lite-2.11.0+git.87517afd72-16.1.x86_64\n--> Processing Dependency: qemu-lite-bin for package: qemu-lite-2.11.0+git.87517afd72-16.1.x86_64\n---> Package qemu-vanilla.x86_64 0:2.11.2+git.0982a56a55-16.1 will be installed\n--> Processing Dependency: qemu-vanilla-data for package: qemu-vanilla-2.11.2+git.0982a56a55-16.1.x86_64\n--> Processing Dependency: qemu-vanilla-bin for package: qemu-vanilla-2.11.2+git.0982a56a55-16.1.x86_64\n--> Running transaction check\n---> Package qemu-lite-bin.x86_64 0:2.11.0+git.87517afd72-16.1 will be installed\n--> Processing Dependency: librbd.so.1()(64bit) for package: qemu-lite-bin-2.11.0+git.87517afd72-16.1.x86_64\n--> Processing Dependency: librados.so.2()(64bit) for package: qemu-lite-bin-2.11.0+git.87517afd72-16.1.x86_64\n--> Processing Dependency: libpixman-1.so.0()(64bit) for package: qemu-lite-bin-2.11.0+git.87517afd72-16.1.x86_64\n---> Package qemu-lite-data.x86_64 0:2.11.0+git.87517afd72-16.1 will be installed\n---> Package qemu-vanilla-bin.x86_64 0:2.11.2+git.0982a56a55-16.1 will be installed\n---> Package qemu-vanilla-data.x86_64 0:2.11.2+git.0982a56a55-16.1 will be installed\n--> Running transaction check\n---> Package librados2.x86_64 1:10.2.5-4.el7 will be installed\n--> Processing Dependency: libboost_random-mt.so.1.53.0()(64bit) for package: 1:librados2-10.2.5-4.el7.x86_64\n--> Processing Dependency: libboost_iostreams-mt.so.1.53.0()(64bit) for package: 1:librados2-10.2.5-4.el7.x86_64\n---> Package librbd1.x86_64 1:10.2.5-4.el7 will be installed\n---> Package pixman.x86_64 0:0.34.0-1.el7 will be installed\n--> Running transaction check\n---> Package boost-iostreams.x86_64 0:1.53.0-27.el7 will be installed\n---> Package boost-random.x86_64 0:1.53.0-27.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package               Arch   Version                     Repository       Size\n================================================================================\nInstalling:\n kata-proxy            x86_64 1.5.0~rc2+git.2029708-14.1  kata_containers 2.5 k\n kata-runtime          x86_64 1.5.0~rc2+git.b954eec-19.1  kata_containers  16 M\n kata-shim             x86_64 1.5.0~rc2+git.4138b29-12.1  kata_containers 2.5 k\nInstalling for dependencies:\n boost-iostreams       x86_64 1.53.0-27.el7               base             61 k\n boost-random          x86_64 1.53.0-27.el7               base             39 k\n kata-containers-image x86_64 1.5.0~rc2-13.1              kata_containers  32 M\n kata-ksm-throttler    x86_64 1.5.0~rc2.git+d70af5c-15.1  kata_containers 5.4 M\n kata-linux-container  x86_64 4.14.67.20-15.1             kata_containers  11 M\n kata-proxy-bin        x86_64 1.5.0~rc2+git.2029708-14.1  kata_containers 1.7 M\n kata-shim-bin         x86_64 1.5.0~rc2+git.4138b29-12.1  kata_containers 6.1 M\n librados2             x86_64 1:10.2.5-4.el7              base            1.8 M\n librbd1               x86_64 1:10.2.5-4.el7              base            2.4 M\n pixman                x86_64 0.34.0-1.el7                base            248 k\n qemu-lite             x86_64 2.11.0+git.87517afd72-16.1  kata_containers 2.5 k\n qemu-lite-bin         x86_64 2.11.0+git.87517afd72-16.1  kata_containers 2.6 M\n qemu-lite-data        x86_64 2.11.0+git.87517afd72-16.1  kata_containers 3.0 M\n qemu-vanilla          x86_64 2.11.2+git.0982a56a55-16.1  kata_containers 2.6 k\n qemu-vanilla-bin      x86_64 2.11.2+git.0982a56a55-16.1  kata_containers 2.6 M\n qemu-vanilla-data     x86_64 2.11.2+git.0982a56a55-16.1  kata_containers 3.0 M\n\nTransaction Summary\n================================================================================\nInstall  3 Packages (+16 Dependent packages)\n\nTotal size: 89 M\nInstalled size: 710 M\nDownloading packages:\n"]}
```

**Comment by egernst** [comment]
I'm seeing:
```
 151s] make -s CONFIG_DEBUG_SECTION_MISMATCH=y ARCH=x86_64 -j all
[  151s] make[2]: Entering directory '/usr/src/packages/BUILD'
[  212s] virtual memory exhausted: Cannot allocate memory
[  218s] virtual memory exhausted: Cannot allocate memory
[  218s] virtual memory exhausted: Cannot allocate memory
[  218s] Segmentation fault
``` 
In the OBS logs for the linux-container projects for debian/ubuntu projects.  I'll need some help from more knowledgable OBS devs (@marcov ?) to make forward progress here.

In the meantime, feel free to checkout the 1.4 stable release, which is posted without issue:
(ie, update ```/etc/apt/sources.list.d/kata-containers.list```):

```
http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/stable-1.4/xUbuntu_18.04/
```
