### ISSUE TITLE
Remove mention of Clear Containers in dev guide

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#33]
The [dev guide](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#assumptions) references Clear Containers packages.

Once we have [packaged components](https://github.com/kata-containers/packaging/issues/1), we need to update the dev guide to reference the Kata packages instead.

**Comment by GabyCT** [comment]
Closing this issue as not longer a reference for Clear Containers packages is being done.
