### ISSUE TITLE
CI: kata-manager.sh is not working correctly 

### ISSUE THREAD

**Issue by chavafg** [kata-containers/documentation#330]
When running the tests using: `01-installing-with-kata-manager.sh`, it uses the OBS `master` directory even if the PR changed it to use  `stable-1.x` to retrieve the packages. 

E.g: http://jenkins.katacontainers.io/job/kata-containers-documentation-ubuntu-16-04-PR/165/console

**Comment by chavafg** [comment]
The issue seems to be https://github.com/kata-containers/documentation/blob/master/.ci/test-install-docs.sh#L99

where we are deleting the `documentation` repository and then it is cloned again using the `kata-manager.sh`[1] but not with the PR changes. 

do we really need to remove the documentation repo at this stage?  
/cc @jodh-intel 

[1] https://raw.githubusercontent.com/kata-containers/tests/master/cmd/kata-manager/kata-manager.sh

**Comment by jodh-intel** [comment]
The repos are deleted here to ensure that the script is not using a local clone - the script must create the entire environment it needs so removes any local clones as it should not rely on them.

Maybe a better (and safer) fix would be to:

- `git clone` / `go get` the repos.
- Check for any locally modified files. If any are found, die.
- `git clean -dfx`.
