### ISSUE TITLE
move the CRI-O configuration related documents together

### ISSUE THREAD

**Issue by gnawux** [kata-containers/documentation#333]
In both architecture and developer guide, there are sections on the configuration of CRI-O. However, both of them are not end-user facing documents. It is better to move them out to `how-to/` or somewhere, and leave links in the original places.

This is the subsequent work of #332, which has moved the containerd configuration doc together in `how-to/`.

**Comment by marcov** [comment]
@gnawux I am taking this issue, since the cri-o docs in the Developer guide is kind of outdated, e.g. `runtime_untrusted_workload` was removed from 1.14 in favor of `RuntimeClass`
