### ISSUE TITLE
Fedora Server 29 Install Fails (Package)

### ISSUE THREAD

**Issue by DarkBlaez** [kata-containers/documentation#345]
Just a from scratch run on new Fedora Server 29 OS

[MIRROR] kata-linux-container-4.14.67.20-16.1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 12193988 but expected size is: 12194172
[FAILED] kata-linux-container-4.14.67.20-16.1.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

DB-

**Comment by jodh-intel** [comment]
Hi @DarkBlaez - Looks like you got unlucky and hit a bad [OBS](https://build.opensuse.org) mirror (outside our control I'm afraid).

Any thought or ideas @mssola, @flavio?

**Comment by DarkBlaez** [comment]
Is there away around this? This happens for most of OS using the script to install. I ask since I am burning time on a bare metal server to specifically pilot this for testing and time is literally money as it is for most I am sure. 

Thanks
DB-

**Comment by jodh-intel** [comment]
Hi @DarkBlaez - I'm afraid I don't know how you can "force" OBS to use another mirror. The documented mirror list for OBS is:

- https://mirrors.opensuse.org/list/bs.html

/cc @mssola, @flavio, @adrianschroeter

**Comment by flavio** [comment]
Hi @jodh-intel. AFAIK there's nothing we can do aside from reporting the issue.

You should follow these steps:

  * Go to https://bugzilla.opensuse.org/enter_bug.cgi?product=openSUSE.org
  * Create an account if you don't already have it
  * Select *"Download Infrastructure"* as component
  * Provide as many information as possible, especially if you know which mirror is the broken one
  * Add me (`fcastelli@<name of our company>.com`, `msabate@<name of our company>.com` to the CC list
