### ISSUE TITLE
Decide on docker version strategy

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#373]
Docker removed devicemapper in 18.09 which complicates life for many (see https://github.com/kata-containers/runtime/pull/1112).

Our [install docs](https://github.com/kata-containers/documentation/tree/master/install) setup the docker repo and then help users *install the latest version of docker*. Given the above, that's a potential problem so we need to find a non-gross way of updating the install docs to install docker 18.06.

The approach needs to:

- be simple.
- work with [`kata-manager`](https://github.com/kata-containers/tests/tree/master/cmd/kata-manager).

Since the docker package will get auto-upgraded from 18.06 -> 18.09 when the user upgrades their installed packages, we're basically going to have to `apt-mark hold` docker I think:

- https://github.com/kata-containers/runtime/issues/926#issuecomment-440689612

We'll also have to find the appropriate distro rune for each other install doc and then remove it if/when docker can be upgraded once again. And add a "note" explaining what the extra step is for.

/cc @egernst.

**Comment by jodh-intel** [comment]
The most annoying bit is going to be having to specify the precise package version of docker the user needs to both install and hold given that, for example, on Ubuntu the user will need to run:

```sh
$ sudo apt -y install docker-ce='18.06.1~ce~3-0~ubuntu'
$ sudo apt-mark hold docker-ce
```

That package version may be different for each distro repo.

**Comment by jodh-intel** [comment]
Related:

- https://github.com/docker/for-linux/issues/452
- https://github.com/docker/cli/pull/1424

**Comment by egernst** [comment]
@jodh-intel -- we have this covered now, right?

**Comment by jodh-intel** [comment]
From an immediate doc perspective, yes, I think this is resolved by https://github.com/kata-containers/documentation/pull/374.

However, that approach can only be a temporary solution as we don't want users to be pinned to what will soon become an old version. As such, re-opening to allow us to discuss a more permanent solution...

**Comment by jodh-intel** [comment]
@kata-containers/architecture-committee - we had to pin docker to version `18.06.2` on https://github.com/kata-containers/documentation/pull/374. But time has moved on and Docker has released the following versions:

- `18.06.3`
- `18.09.0`
- `18.09.1`
- `18.09.2`
- `18.09.3`

We need to remove the requirement that users stay on docker `18.06`.

**Comment by chavafg** [comment]
https://github.com/kata-containers/documentation/pull/409 has landed, should we also change our  [versions.yaml](https://github.com/kata-containers/runtime/blob/master/versions.yaml#L208) to use 18.09 ? We are still testing with 18.06... So far all docker testing is using `overlay`

**Comment by jodh-intel** [comment]
+1 for moving to 18.09 as that is now what users will be installing by default if they follow our install guides.

/cc @ganeshmaharaj, @amshinde, @mcastelino.
