### ISSUE TITLE
SR-IOV for AMD/mxGPU

### ISSUE THREAD

**Issue by rrichardson** [kata-containers/documentation#400]
Is anyone looking into virtualizing AMD mxGPU cards with https://github.com/GPUOpen-LibrariesAndSDKs/MxGPU-Virtualization  for SR-IOV? 

I would like to be able to present multiple containers on a host with a virtualized AMD GPU.  This would be both for tensorflow as well as more graphics-framebuffer oriented projects.

**Comment by grahamwhaley** [comment]
@rrichardson - I don't know if these might help, but there are both SRIOV and an Intel GPU passthrough doc over at https://github.com/kata-containers/documentation/tree/master/use-cases
afaik, the only AMD specific things we've had so far have been around a security enclave style feature, and not GPU... unless somebody else knows different.

**Comment by rrichardson** [comment]
@grahamwhaley - that's an excellent resource.  Thanks.  Now to see if I can find some corresponding "client" kernel settings for the AMD open source drivers.
