### ISSUE TITLE
Unpin docker and move to latest version

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#407]
#374 pinned docker to the last known good version of docker that supported device-mapper. However, as shown in https://github.com/kata-containers/documentation/issues/373#issuecomment-475152776, docker has released a number of new versions.

Undo the pinning and switch strategy to simply make a note to users that if they wish to use a feature such as device-mapper, they will need to look at alternative configurations.

**Comment by ganeshmaharaj** [comment]
The two alternate device mapper / lvm solutions for containerd are.
1. https://github.com/firecracker-microvm/firecracker-containerd/tree/master/snapshotter/cmd/devmapper
2. https://github.com/ganeshmaharaj/lvm-snapshotter

Both of them are for containerd. devicemapper will currently pending merging into containerd upstream repo via https://github.com/containerd/containerd/pull/3022.
crio supports a similar LVM /devicemapper snapshotter. 

It would be nice to tell the user that if they wish to use a block backend for docker they can run the stand-alone versions of the snapshotter until the backend lands after which they can use devicemapper / lvm as their backends.

**Comment by jodh-intel** [comment]
Thanks @ganeshmaharaj - I've added a note to all the docker install guides on #409 pointing back at this issue so users can find details on alternatives.

**Comment by ganeshmaharaj** [comment]
A latest update from docker engineering team. They are currently working to make docker use containerd to as the default storage handler. Refer to comment https://github.com/docker/for-linux/issues/452#issuecomment-477538868. Hopefully the two changes referenced there will land soon. We will keep an eye on those and update once they land in mainstream docker.

**Comment by zeigerpuppy** [comment]
looks like it's fixed in docker-ce 19.03.1 and upwards.  I haven't tested yet on my Devuan box...

https://github.com/docker/for-linux/issues/452#issuecomment-497486728
