### ISSUE TITLE
document docker in kata

### ISSUE THREAD

**Issue by egernst** [kata-containers/documentation#414]
We should document how to run docker from within a Kata container. 

This addresses https://github.com/kata-containers/runtime/issues/358

**Comment by grahamwhaley** [comment]
I have some dibs on what we call this.... along the lines of 'dind' for Docker-In-Docker ... I reckon....
Docker-In-Kata is 'dink'
Kata-In-Kata is 'kink'

:-)

**Comment by jodh-intel** [comment]
Let's stop dinking around and see how kinky boots! :smile:

**Comment by jcvenegas** [comment]
@egernst @grahamwhaley have you consider use CONFIG_OVERLAY_FS=y by default in our kernel, or you think is not an strong usecase to enable it?

**Comment by grahamwhaley** [comment]
@jcvenegas it's not been on my radar before - is that something we need to have for DinK to work? If so, we can for sure consider adding it.

**Comment by jcvenegas** [comment]
@grahamwhaley  looking to @egernst  commit seems that is the recommended fs to use  and builds a kernel manually. Probably we can make the process less painful if we add it by default.

**Comment by egernst** [comment]
related issue: https://github.com/kata-containers/runtime/issues/1429

**Comment by AkihiroSuda** [comment]
Docker-in-Kata doesn't seem to make sense for security, until Kata get support for `--privileged` without exposing host devices https://github.com/kata-containers/runtime/issues/1568
