### ISSUE TITLE
improve organization of documentation repo

### ISSUE THREAD

**Issue by egernst** [kata-containers/documentation#417]
We could use some shuffling/cleanup.
- [x] move Zun and its artifacts to use cases: https://github.com/egernst/documentation/commit/39cd6aa62603e932243290efc026ed3463371e07
- [ ] reference constraints document from architecture/design mds
- [x] move constraints.md under design folder, reference from architecture.md?
- [x] move Vsocks.md to design folder, reference from architecture.md?
- [ ] create a processes folder, and move relevant .mds under here
- [ ] review top level of README for usefullness. 
- [ ] need to make sure each .md is referenced at least once

**Comment by egernst** [comment]
/cc @eadamsintel @devimc 
@gabibeyer @ganeshmaharaj  - as new(er) contributors to the code base, I could use your help in viewing our design/architecture docs and providing some fresh insights into usability.

/cc @jodh-intel  @grahamwhaley FYI.

**Comment by egernst** [comment]
@mimeriza  - if you have cycles, this may actually work well for you, too.

**Comment by eadamsintel** [comment]
I would consider combiningg the "how to" folder with the "use case" folder.  You could call it "user guides"  It is not obvious which folder a user would want to click on.  I might think how do I use this with a GPU device and you would have to look in the "use case" folder.  There should probably be a rather large guide on how to use kata with kubernetes that goes into runtimeclass, how to use kata-deploy, etc.. and it should appropriately reference the architecture guide when talking about networking or storage and how it works with kubernetes.  The kubernetes information is spread throughout the other guides but users that just want to jump in and get started wouldn't care necessarily about other design aspects of kata.  As part of this I would move kata-deploy instructions to the install folder for people that would think to go there for kubernetes integration instructions. This can be referenced by a kubernetes guide in the how to section.

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/tests/issues/1316.
