### ISSUE TITLE
Apply a tomcat server, but cannot access

### ISSUE THREAD

**Issue by wubo0067** [kata-containers/documentation#421]
1. Pods
[root@katak8s-1 calmwu]# kubectl get pod -o wide --all-namespaces
NAMESPACE     NAME                                READY   STATUS    RESTARTS   AGE   IP              NODE        NOMINATED NODE   READINESS GATES
default       **calmwupod**                           1/1     Running   0          31m   10.244.0.14     katak8s-1   <none>           <none>
kube-system   coredns-7d98bc987b-dxpc7            1/1     Running   27         9h    10.244.0.12     katak8s-1   <none>           <none>
kube-system   coredns-7d98bc987b-hqtsc            1/1     Running   26         9h    10.244.0.13     katak8s-1   <none>           <none>
kube-system   etcd-katak8s-1                      1/1     Running   6          9h    192.168.6.201   katak8s-1   <none>           <none>
kube-system   kube-apiserver-katak8s-1            1/1     Running   8          9h    192.168.6.201   katak8s-1   <none>           <none>
kube-system   kube-controller-manager-katak8s-1   1/1     Running   2          9h    192.168.6.201   katak8s-1   <none>           <none>
kube-system   kube-flannel-ds-amd64-pb5bd         1/1     Running   1          9h    192.168.6.201   katak8s-1   <none>           <none>
kube-system   kube-proxy-qs69l                    1/1     Running   1          9h    192.168.6.201   katak8s-1   <none>           <none>
kube-system   kube-scheduler-katak8s-1            1/1     Running   7          9h    192.168.6.201   katak8s-1   <none>           <none>

2. svc
[root@katak8s-1 calmwu]# kubectl get svc -o wide --all-namespaces
NAMESPACE     NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE   SELECTOR
default       **calmwusvc**    NodePort    10.104.65.228   <none>        9090:30002/TCP   9h    app=calmwupod
default       kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP          9h    <none>
kube-system   kube-dns     ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP    9h    k8s-app=kube-dns

3. ep
[root@katak8s-1 calmwu]# kubectl get ep -o wide --all-namespaces
NAMESPACE     NAME                      ENDPOINTS                                                  AGE
default       **calmwusvc                 10.244.0.14:8080**                                           9h
default       kubernetes                192.168.6.201:6443                                         9h
kube-system   kube-controller-manager   <none>                                                     9h
kube-system   kube-dns                  10.244.0.12:53,10.244.0.13:53,10.244.0.12:53 + 1 more...   9h
kube-system   kube-scheduler            <none>                                                     9h

4. kata-runtime ps
[root@katak8s-1 calmwu]# kata-runtime ps f49138e8ce1d2a0b5e5df7e59b98bab376c6c55f3a770ff47c5705e8021992e5
UID        PID  PPID  C STIME TTY          TIME CMD
root       126    99  0 02:57 ?        00:00:10 **/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java** -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.endorsed.dirs=/usr/local/tomcat/endorsed -classpath /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/usr/local/tomcat -Dcatalina.home=/usr/local/tomcat -Djava.io.tmpdir=/usr/local/tomcat/temp org.apache.catalina.startup.Bootstrap start

Now execute the following command failed！
 [root@katak8s-1 calmwu]# telnet 10.244.0.14 8080
Trying 10.244.0.14...
**telnet: connect to address 10.244.0.14: Connection refused**

ping is ok
[root@katak8s-1 calmwu]# ping 10.244.0.14
PING 10.244.0.14 (10.244.0.14) 56(84) bytes of data.
64 bytes from 10.244.0.14: icmp_seq=1 ttl=64 time=0.048 ms
64 bytes from 10.244.0.14: icmp_seq=2 ttl=64 time=0.110 ms

I want access tomcat server，but failed!

**Comment by wubo0067** [comment]
pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: calmwupod
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
  labels:
    app: calmwupod #service通过该标签与其对应
spec:
  containers:
  - name: calmwupod
    image: kubeguide/tomcat-app:v1
    ports:
    - containerPort: 9090

svc.yaml
apiVersion: v1
kind: Service #表明是kubernetes Service
metadata:
  name: calmwusvc #service的全局唯一名称
spec:
  type: NodePort #开启了NodePort方式的外网访问
  ports:
    - port: 9090 #service提供服务的端口号
      targetPort: 8080 #这里是容器的端口，需要指定，不然会默认使用9090
      nodePort: 30002 #在k8s之外，用户使用30001端口访问myweb的虚端口
  selector: 
    app: calmwupod

**Comment by wubo0067** [comment]
kata-env

[root@katak8s-1 calmwu]# kata-runtime kata-env
[Meta]
  Version = "1.0.20"

[Runtime]
  Debug = true
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  Path = "/usr/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.6.0-rc2"
    Commit = "8e72cf1"
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/etc/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.11.0\nCopyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-lite-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = true
  UseVSock = false

[Image]
  Path = "/usr/share/kata-containers/kata-containers-centos-with-debug-console.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.19.24.31-21.1.container"
  Parameters = "init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket systemd.mask=systemd-journald.service systemd.mask=systemd-journald.socket systemd.mask=systemd-journal-flush.service systemd.mask=systemd-udevd.service systemd.mask=systemd-udevd.socket systemd.mask=systemd-udev-trigger.service systemd.mask=systemd-timesyncd.service systemd.mask=systemd-update-utmp.service systemd.mask=systemd-tmpfiles-setup.service systemd.mask=systemd-tmpfiles-cleanup.service systemd.mask=systemd-tmpfiles-cleanup.timer systemd.mask=tmp.mount agent.log=debug initcall_debug"

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.6.0-rc2-d4aa0b2"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.6.0-rc2-ea27044"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = true

[Agent]
  Type = "kata"

[Host]
  Kernel = "3.10.0-862.el7.x86_64"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = false
  [Host.Distro]
    Name = "CentOS Linux"
    Version = "7"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz"

[Netmon]
  Version = "kata-netmon version 1.6.0-rc2"
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = true
  Enable = false

**Comment by gnawux** [comment]
@wubo0067 Does port 9090 work?

**Comment by wubo0067** [comment]
> @wubo0067 Does port 9090 work?
no, telnet 10.104.65.228 9090, Connection refused

**Comment by wubo0067** [comment]
Who can explain the network model of kata, how to interact with virtual machines under the Flannel network

**Comment by wubo0067** [comment]
In container networking namespace, can't find "clear conainers bridge" interface.

[root@katak8s-1 calmwu]# ip netns exec cni-822a0ff2-06de-e4c3-2875-c81bf9be9ad0 ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether b6:2b:fa:e4:8e:2a brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.233.0.14/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::b42b:faff:fee4:8e2a/64 scope link tentative dadfailed 
       valid_lft forever preferred_lft forever

**Comment by gnawux** [comment]
@wubo0067 I think you'd better ask the questions in [slack channel](https://katacontainers.slack.com/), and here is the [slack invitation link](http://bit.ly/KataSlack) in case you need it.

**Comment by wubo0067** [comment]
> @wubo0067 I think you'd better ask the questions in [slack channel](https://katacontainers.slack.com/), and here is the [slack invitation link](http://bit.ly/KataSlack) in case you need it.

Thank you!!!

**Comment by amshinde** [comment]
@wubo0067  You mentioned you are getting this error:

> [root@katak8s-1 calmwu]# telnet 10.244.0.14 8080
> Trying 10.244.0.14...
> **telnet: connect to address 10.244.0.14: Connection refused**

But do you have a telnet server there ?
I tried to reproduce this first with runc, and I see there is a web server that is started by the app,
so I can curl to 10.244.0.14 8080. I can do the same with kata.
So unless, I have missed something in your setup, the tomcat web server is correctly exposed with kata and `curl   10.244.0.14:8080` should work.

**Comment by wubo0067** [comment]
@amshinde I used nginx instead of tomcat, use same pod.yaml,

**crio config: default_workload_trust = "trusted" use runc**
[root@192 kata-nginx]# kubectl get pod -o wide
NAME              READY   STATUS    RESTARTS   AGE     IP            NODE             NOMINATED NODE   READINESS GATES
nginx-untrusted   1/1     Running   0          2m50s   10.244.0.15   192.168.36.129   <none>           <none>

[root@192 kata-nginx]# telnet 10.244.0.15 80
Trying 10.244.0.15...
Connected to 10.244.0.15.
Escape character is '^]'.
ok, connect successed!

**crio config: default_workload_trust = "untrusted" use kata**
[root@192 kata-nginx]# systemctl daemon-reload 
[root@192 kata-nginx]# systemctl restart crio

[root@192 kata-nginx]# kubectl get pod -o wide
NAME              READY   STATUS    RESTARTS   AGE   IP            NODE             NOMINATED NODE   READINESS GATES
nginx-untrusted   1/1     Running   0          33s   10.244.0.18   192.168.36.129   <none>           <none>

[root@192 kata-nginx]# telnet 10.244.0.18 80
Trying 10.244.0.18...
**telnet: connect to address 10.244.0.18: Connection refused**

**Comment by wubo0067** [comment]
@amshinde 
@amshinde I used nginx instead of tomcat, use same pod.yaml,

crio config: default_workload_trust = "trusted" use runc
[root@192 kata-nginx]# kubectl get pod -o wide
NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE READINESS GATES
nginx-untrusted 1/1 Running 0 2m50s 10.244.0.15 192.168.36.129

[root@192 kata-nginx]# telnet 10.244.0.15 80
Trying 10.244.0.15...
Connected to 10.244.0.15.
Escape character is '^]'.
ok, connect successed!

crio config: default_workload_trust = "untrusted" use kata
[root@192 kata-nginx]# systemctl daemon-reload
[root@192 kata-nginx]# systemctl restart crio

[root@192 kata-nginx]# kubectl get pod -o wide
NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE READINESS GATES
nginx-untrusted 1/1 Running 0 33s 10.244.0.18 192.168.36.129

[root@192 kata-nginx]# telnet 10.244.0.18 80
Trying 10.244.0.18...
telnet: connect to address 10.244.0.18: Connection refused

**Comment by wubo0067** [comment]
@amshinde Feel that QEMU virtual machines are not connected to the external network

**Comment by wubo0067** [comment]
@amshinde 
kata-runtime 
internetworking_model="macvtap"

qemu cmd:
/usr/bin/qemu-lite-system-x86_64 -name sandbox-1ef84face47495ca60e7e893fffbd911cc582d974b5b16e19d8357c2f91cb4b7 -uuid 16963d4c-4f15-4c56-81e8-7645cee5a189 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host,pmu=off -qmp unix:/run/vc/vm/1ef84face47495ca60e7e893fffbd911cc582d974b5b16e19d8357c2f91cb4b7/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=8831M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=true,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/1ef84face47495ca60e7e893fffbd911cc582d974b5b16e19d8357c2f91cb4b7/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/share/kata-containers/kata-containers-image_clearlinux_1.6.0-rc2_agent_a41f322af86.img,size=134217728 -device virtio-scsi-pci,id=scsi0,disable-modern=true,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng,rng=rng0,romfile= -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/1ef84face47495ca60e7e893fffbd911cc582d974b5b16e19d8357c2f91cb4b7/kata.sock,server,nowait -device virtio-9p-pci,disable-modern=true,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/1ef84face47495ca60e7e893fffbd911cc582d974b5b16e19d8357c2f91cb4b7,security_model=none -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -kernel /usr/share/kata-containers/vmlinuz-4.19.24.31-21.1.container -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 quiet systemd.show_status=false panic=1 nr_cpus=4 init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket systemd.mask=systemd-journald.service systemd.mask=systemd-journald.socket systemd.mask=systemd-journal-flush.service systemd.mask=systemd-udevd.service systemd.mask=systemd-udevd.socket systemd.mask=systemd-udev-trigger.service systemd.mask=systemd-timesyncd.service systemd.mask=systemd-update-utmp.service systemd.mask=systemd-tmpfiles-setup.service systemd.mask=systemd-tmpfiles-cleanup.service systemd.mask=systemd-tmpfiles-cleanup.timer systemd.mask=tmp.mount -pidfile /run/vc/vm/1ef84face47495ca60e7e893fffbd911cc582d974b5b16e19d8357c2f91cb4b7/pid -smp 1,cores=1,threads=1,sockets=1,maxcpus=4

**Comment by wubo0067** [comment]
@amshinde QEMU virtual machine want to join the flannel network, must have bridge device or other, will eth0 and tapX network port to join the bridge。
There is a network configuration in /usr/share/defaults/kata-containers/configuration.toml file, but why Kata-runtime did not create the relevant device, and there are no network parameters in the QEMU command

**Comment by amshinde** [comment]
@wubo0067 Your qemu command line should have a net device, the fact that you are not seeing one in your command line 
Can you post details of your k8s stack here? What version of k8s are you using, are you using crio or containerd and is this shim v2.
Finally can you post the output of  `kata-collect-data.sh` script here.

**Comment by wubo0067** [comment]
@amshinde The problem occurs on the Kata-netmon service, which is going to build brige, tap, and add interfaces to the VM。

**Comment by amshinde** [comment]
@wubo0067 Ok, I see what the issue could be now, do you have `manage_network_ns_lifecycle` set to `false` in your /etc/crio/crio.conf file. Can you set that to `true`, restart crio with `systemctl restart crio.service` and then try.

**Comment by wubo0067** [comment]
@amshinde I didn;t find manage_network_ns_lifecycle this option in file crio.conf.

ciro.conf


# The "crio" table contains all of the server options.
[crio]

# CRI-O reads its storage defaults from the containers/storage configuration
# file, /etc/containers/storage.conf. Modify storage.conf if you want to
# change default storage for all tools that use containers/storage.  If you
# want to modify just crio, you can change the storage configuration in this
# file.

# root is a path to the "root directory". CRIO stores all of its data,
# including container images, in this directory.
root = "/var/lib/containers/storage"

# run is a path to the "run directory". CRIO stores all of its state
# in this directory.
runroot = "/var/run/containers/storage"

# storage_driver select which storage driver is used to manage storage
# of images and containers.
#storage_driver = ""

# storage_option is used to pass an option to the storage driver.
#storage_option = [
#]

# The "crio.api" table contains settings for the kubelet/gRPC interface.
[crio.api]

# listen is the path to the AF_LOCAL socket on which crio will listen.
listen = "/var/run/crio/crio.sock"

# stream_address is the IP address on which the stream server will listen
stream_address = ""

# stream_port is the port on which the stream server will listen
stream_port = "10010"

# stream_enable_tls enables encrypted tls transport of the stream server
stream_enable_tls = false

# stream_tls_cert is the x509 certificate file path used to serve the encrypted stream.
# This file can change, and CRIO will automatically pick up the changes within 5 minutes.
stream_tls_cert = ""

# stream_tls_key is the key file path used to serve the encrypted stream.
# This file can change, and CRIO will automatically pick up the changes within 5 minutes.
stream_tls_key = ""

# stream_tls_ca is the x509 CA(s) file used to verify and authenticate client
# communication with the tls encrypted stream.
# This file can change, and CRIO will automatically pick up the changes within 5 minutes.
stream_tls_ca = ""

# file_locking is whether file-based locking will be used instead of
# in-memory locking
file_locking = false

# The "crio.runtime" table contains settings pertaining to the OCI
# runtime used and options for how to set up and manage the OCI runtime.
[crio.runtime]

# runtime is the OCI compatible runtime used for trusted container workloads.
# This is a mandatory setting as this runtime will be the default one
# and will also be used for untrusted container workloads if
# runtime_untrusted_workload is not set.
runtime = "/usr/sbin/runc"

# runtime_untrusted_workload is the OCI compatible runtime used for untrusted
# container workloads. This is an optional setting, except if
# default_container_trust is set to "untrusted".
runtime_untrusted_workload = "/usr/bin/kata-runtime"

# default_workload_trust is the default level of trust crio puts in container
# workloads. It can either be "trusted" or "untrusted", and the default
# is "trusted".
# Containers can be run through different container runtimes, depending on
# the trust hints we receive from kubelet:
# - If kubelet tags a container workload as untrusted, crio will try first to
# run it through the untrusted container workload runtime. If it is not set,
# crio will use the trusted runtime.
# - If kubelet does not provide any information about the container workload trust
# level, the selected runtime will depend on the default_container_trust setting.
# If it is set to "untrusted", then all containers except for the host privileged
# ones, will be run by the runtime_untrusted_workload runtime. Host privileged
# containers are by definition trusted and will always use the trusted container
# runtime. If default_container_trust is set to "trusted", crio will use the trusted
# container runtime for all containers.
default_workload_trust = "untrusted"

# no_pivot instructs the runtime to not use pivot_root, but instead use MS_MOVE
no_pivot = false

# conmon is the path to conmon binary, used for managing the runtime.
conmon = "/usr/libexec/crio/conmon"

# conmon_env is the environment variable list for conmon process,
# used for passing necessary environment variable to conmon or runtime.
conmon_env = [
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
]

# selinux indicates whether or not SELinux will be used for pod
# separation on the host. If you enable this flag, SELinux must be running
# on the host.
selinux = true

# seccomp_profile is the seccomp json profile path which is used as the
# default for the runtime.
seccomp_profile = "/etc/crio/seccomp.json"

# apparmor_profile is the apparmor profile name which is used as the
# default for the runtime.
apparmor_profile = "crio-default"

# cgroup_manager is the cgroup management implementation to be used
# for the runtime.
cgroup_manager = "cgroupfs"

# default_capabilities is the list of capabilities to add and can be modified here.
# If capabilities below is commented out, the default list of capabilities defined in the
# spec will be added.
# If capabilities is empty below, only the capabilities defined in the container json
# file by the user/kube will be added.
default_capabilities = [
	"CHOWN", 
	"DAC_OVERRIDE", 
	"FSETID", 
	"FOWNER", 
	"NET_RAW", 
	"SETGID", 
	"SETUID", 
	"SETPCAP", 
	"NET_BIND_SERVICE", 
	"SYS_CHROOT", 
	"KILL", 
]

# hooks_dir_path is the oci hooks directory for automatically executed hooks
hooks_dir_path = "/usr/share/containers/oci/hooks.d"

# default_mounts is the mounts list to be mounted for the container when created
# deprecated, will be taken out in future versions, add default mounts to either
# /usr/share/containers/mounts.conf or /etc/containers/mounts.conf
default_mounts = [
	"/usr/share/rhel/secrets:/run/secrets", 
]

# CRI-O reads its default mounts from the following two files:
# 1) /etc/containers/mounts.conf - this is the override file, where users can
# either add in their own default mounts, or override the default mounts shipped
# with the package.
# 2) /usr/share/containers/mounts.conf - this is the default file read for mounts.
# If you want CRI-O to read from a different, specific mounts file, you can change
# the default_mounts_file path right below. Note, if this is done, CRI-O will only add
# mounts it finds in this file.

# default_mounts_file is the file path holding the default mounts to be mounted for the
# container when created.
# default_mounts_file = ""

# pids_limit is the number of processes allowed in a container
pids_limit = 1024

# log_size_max is the max limit for the container log size in bytes.
# Negative values indicate that no limit is imposed.
log_size_max = -1

# read-only indicates whether all containers will run in read-only mode
read_only = false

# log_level changes the verbosity of the logs printed.
# Options are: error (default), fatal, panic, warn, info, and debug
log_level = "error"

# The "crio.image" table contains settings pertaining to the
# management of OCI images.

# uid_mappings specifies the UID mappings to have in the user namespace.
# A range is specified in the form containerUID:HostUID:Size.  Multiple
# ranges are separed by comma.
uid_mappings = ""

# gid_mappings specifies the GID mappings to have in the user namespace.
# A range is specified in the form containerGID:HostGID:Size.  Multiple
# ranges are separed by comma.
gid_mappings = ""

[crio.image]

# default_transport is the prefix we try prepending to an image name if the
# image name as we receive it can't be parsed as a valid source reference
default_transport = "docker://"

# pause_image is the image which we use to instantiate infra containers.
#pause_image = "k8s.gcr.io/pause:3.1"
pause_image = "docker.io/littlebull/pause:3.1"

# pause_command is the command to run in a pause_image to have a container just
# sit there.  If the image contains the necessary information, this value need
# not be specified.
pause_command = "/pause"

# signature_policy is the name of the file which decides what sort of policy we
# use when deciding whether or not to trust an image that we've pulled.
# Outside of testing situations, it is strongly advised that this be left
# unspecified so that the default system-wide policy will be used.
signature_policy = ""

# image_volumes controls how image volumes are handled.
# The valid values are mkdir and ignore.
image_volumes = "mkdir"

# CRI-O reads its configured registries defaults from the containers/image configuration
# file, /etc/containers/registries.conf. Modify registries.conf if you want to
# change default registries for all tools that use containers/image.  If you
# want to modify just crio, you can change the registies configuration in this
# file.

# insecure_registries is used to skip TLS verification when pulling images.
# insecure_registries = [
# ]

# registries is used to specify a comma separated list of registries to be used
# when pulling an unqualified image (e.g. fedora:rawhide).
registries = ['registry.access.redhat.com', 'registry.fedoraproject.org', 'docker.io']

# The "crio.network" table contains settings pertaining to the
# management of CNI plugins.
[crio.network]

# network_dir is is where CNI network configuration
# files are stored.
network_dir = "/etc/cni/net.d/"

# plugin_dir is is where CNI plugin binaries are stored.
plugin_dir = "/usr/libexec/cni"

**Comment by wubo0067** [comment]
@amshinde Thank you so much!!!

add manage_network_ns_lifecycle to crio.conf

**tap device created successfully**
[root@katak8s-1 kata-nginx]# ip netns exec k8s_kata-nginxpod_default_1534db7c-5c1f-11e9-8165-000c2999b03d_0-92ecb879 bash
[root@katak8s-1 kata-nginx]# ip link list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
3: eth0@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 4a:f9:e8:13:b3:73 brd ff:ff:ff:ff:ff:ff link-netnsid 0
**51901: tap0_kata@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1500
    link/ether a2:9b:ce:8a:77:39 brd ff:ff:ff:ff:ff:ff**

hahaha~~~,It's through the network with the VM!!
telnet> [root@katak8s-1 kata-nginx]# telnet 10.233.0.60 80
Trying 10.233.0.60...
Connected to 10.233.0.60.
Escape character is '^]'.
Connection closed by foreign host.
[root@katak8s-1 kata-nginx]# kubectl get pod -o wide
NAME              READY   STATUS    RESTARTS   AGE     IP            NODE        NOMINATED NODE   READINESS GATES
kata-nginxpod     1/1     Running   0          5m35s   10.233.0.60   katak8s-1   <none>           <none>
nginx-untrusted   1/1     Running   11         13d     10.233.0.58   katak8s-1   <none>           <none>
