### ISSUE TITLE
Kata containers with containerd and k8s document is cyclical

### ISSUE THREAD

**Issue by dmiyoshi1** [kata-containers/documentation#422]
Hi; I have been trying to follow the howto for Kata containers with containerd and k8s.  As I follow the document there are a lot of links to other install/config documents.  And it seems like k8s is installed and init'd multiple times.  Is there a way to clean that up to reflect where k8s init should not be executed?  Or where k8s must be torn down before other steps are executed?

The confusing part is during the cri-containerd instll.  To complete the cri-containerd installation steps k8s is installed.  Then k8s is installed again in subsequent steps howto step.

Thanks.

Dennis

**Comment by grahamwhaley** [comment]
Hi @dmiyoshi1 - I think somebody had plans to amalgamate and improve the k8s install documentation - I think it was one of @gnawux @bergwolf ? @egernst may also have input.

**Comment by wubo0067** [comment]
@dmiyoshi1 
If you want to know K8s+crio+kata's cluster deployment, I can give you the documentation I wrote, but it's in Chinese.

**Comment by dmiyoshi1** [comment]
Hi @grahamwhaley - thanks I'll wait for replies in this thread.

**Comment by dmiyoshi1** [comment]
Hi @grahamwhaley - I'll watch for comments/replies here.  Of course after I reopen the thread.  :)

**Comment by dmiyoshi1** [comment]
Hi @wubo0067
I'll have to pass on the document in Chinese.  Thanks anyway.

**Comment by bergwolf** [comment]
@dmiyoshi1 I have [a blog](http://bergwolf.github.io/2019/02/01/install-kata-containers-for-docker-kubernetes.html) about it. Didn't push it here as the content is not really an official document but just a record of how I install my k8s+containerd+kata and docker+kata testing environment. You would likely be able to get a working setup following it but YMMV.

**Comment by dmiyoshi1** [comment]
@bergwolf I will check out the blog.  I did find that I could make progress through the configuration using the current howto if I did not init k8s until the end of the process.  But I've looked at your blog and it is many times easier to follow.  Thanks.

**Comment by dmiyoshi1** [comment]
All;  I want to send out a thank you to everyone who responded.  I have made it through the how-to and have found that I do not need to accomplish the final k8s steps because they were executed prior.  Thank you again.
