### ISSUE TITLE
Need to doc the network `internetworking_model` options

### ISSUE THREAD

**Issue by wenlxie** [kata-containers/documentation#427]
I know we now have multiple internetworking model for kata like macvtap, bridged, tcfilter.
It is better to have a doc about  these working models for users. 
For user to use kata, network is one of the important part they care about.

**Comment by wubo0067** [comment]
@wenlxie If you're free, you can take a look at this code.
github.com\kata-containers\runtime\virtcontainers\sandbox.go:(s *Sandbox) createNetwork()

**Comment by wenlxie** [comment]
@wubo0067 Actually I had view these codes before.
Just create this issue for that other customers may need this.
