### ISSUE TITLE
Install fails on Debian 9: dockerd complains directives are specified both as a flag and in the configuration file

### ISSUE THREAD

**Issue by olberger** [kata-containers/documentation#442]
After running the install script per https://github.com/kata-containers/documentation/blob/master/install/installing-with-kata-manager.md#full-installation on Debian 9, dockerd fails to start.

Looking at the syslog I get:
```
Apr 24 11:27:25 inf-11847 systemd[1]: Starting Docker Application Container Engine...
Apr 24 11:27:25 inf-11847 dockerd[824]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: default-runtime: (from flag: kata-runtime, from file: kata-runtime)
Apr 24 11:27:25 inf-11847 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 24 11:27:25 inf-11847 systemd[1]: Failed to start Docker Application Container Engine.
```

**Comment by olberger** [comment]
I edited /etc/systemd/system/docker.service.d/kata-containers.conf and removed the default runtime setting there, since it was already in /etc/docker/daemon.json

That seems to work around the issue

**Comment by grahamwhaley** [comment]
Hi @olberger - thanks for reporting!
Was this the first/only clean install of kata on that system?
It looks, from the error, that kata has been configured as a docker runtime both in the docker config .json (maybe `/etc/docker/*`), and on the docker commandline startup (in a systemd config file maybe, like `/etc/systemd/system/docker*` ?).
I would not expect `kata-manager` to configure both, which is why I ask if this was a clean install?

/cc @jcvenegas @egernst

**Comment by olberger** [comment]
What may have happened is I launched the script several times (curl wasn't there initially, and no check was made for this prerequisite), which may have lead to that situation.

I think I'll try and reproduce.

**Comment by grahamwhaley** [comment]
@olberger - thanks - it'd be great if you can reproduce.
Ideally the script would be idempotent.
If the `runtime` had been configured in multiple places, then I suspect it was probably not the script that did that, as I'd expect it to only operate on one place, always. Let us know!, and **thanks**

**Comment by olberger** [comment]
FYI, redid install on a frehs Debian 9 (with curl), and got:
```
Traitement des actions différées (« triggers ») pour systemd (232-25+deb9u11) ...
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -D --add-runtime kata-runtime=/usr/bin/kata-runtime --default-runtime=kata-runtime
[....] Stopping docker (via systemctl): docker.serviceWarning: docker.service changed on disk. Run 'systemctl daemon-reload' to reload units.
. ok 
[....] Starting docker (via systemctl): docker.serviceWarning: docker.service changed on disk. Run 'systemctl daemon-reload' to reload units.
. ok 
tail: impossible d'ouvrir '/var/log/docker.log' en lecture: Aucun fichier ou dossier de ce type
tail: aucun fichier restant
```
(excuse the french locale)

```
# cat /etc/docker/daemon.json 
{
"default-runtime": "kata-runtime",
"runtimes": {
"kata-runtime": {
"path": "/usr/bin/kata-runtime"
}
}
}
```
I performed the systemctl daemon-reload as instructed, and did start docker, and then got:
```
# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─kata-containers.conf
   Active: active (running) since Wed 2019-04-24 13:41:04 CEST; 5min ago
     Docs: https://docs.docker.com
 Main PID: 9293 (dockerd)
      CPU: 275ms
   CGroup: /system.slice/docker.service
           └─9293 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

avril 24 13:41:04 inf-11847 dockerd[9293]: time="2019-04-24T13:41:04.580549072+02:00" level=warning msg="Your kernel does not support swap memory limit"
avril 24 13:41:04 inf-11847 dockerd[9293]: time="2019-04-24T13:41:04.580588284+02:00" level=warning msg="Your kernel does not support cgroup rt period"
avril 24 13:41:04 inf-11847 dockerd[9293]: time="2019-04-24T13:41:04.580598634+02:00" level=warning msg="Your kernel does not support cgroup rt runtime"
avril 24 13:41:04 inf-11847 dockerd[9293]: time="2019-04-24T13:41:04.580957574+02:00" level=info msg="Loading containers: start."
avril 24 13:41:04 inf-11847 dockerd[9293]: time="2019-04-24T13:41:04.652550638+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be use
avril 24 13:41:04 inf-11847 dockerd[9293]: time="2019-04-24T13:41:04.684430286+02:00" level=info msg="Loading containers: done."
avril 24 13:41:04 inf-11847 dockerd[9293]: time="2019-04-24T13:41:04.734335560+02:00" level=info msg="Docker daemon" commit=e8ff056 graphdriver(s)=overlay2 version=18.09.5
avril 24 13:41:04 inf-11847 dockerd[9293]: time="2019-04-24T13:41:04.734406816+02:00" level=info msg="Daemon has completed initialization"
avril 24 13:41:04 inf-11847 dockerd[9293]: time="2019-04-24T13:41:04.742204429+02:00" level=info msg="API listen on /var/run/docker.sock"
avril 24 13:41:04 inf-11847 systemd[1]: Started Docker Application Container Engine.
```
Strange, as it doesn't look like ExecStart=/usr/bin/dockerd -D --add-runtime kata-runtime=/usr/bin/kata-runtime --default-runtime=kata-runtime

I'm a bit puzzled...

**Comment by olberger** [comment]
OK, and now if I do:
# systemctl stop docker.service
and 
# systemctl start docker.service 
again, I get the issue again:
```
# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─kata-containers.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-04-24 13:49:00 CEST; 905ms ago
     Docs: https://docs.docker.com
  Process: 9803 ExecStart=/usr/bin/dockerd -D --add-runtime kata-runtime=/usr/bin/kata-runtime --default-runtime=kata-runtime (code=exited, status=1/FAILURE)
 Main PID: 9803 (code=exited, status=1/FAILURE)
      CPU: 80ms

avril 24 13:49:00 inf-11847 systemd[1]: docker.service: Unit entered failed state.
avril 24 13:49:00 inf-11847 systemd[1]: docker.service: Failed with result 'exit-code'.
```
Indeed:
```
# cat /etc/systemd/system/docker.service.d/kata-containers.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -D --add-runtime kata-runtime=/usr/bin/kata-runtime --default-runtime=kata-runtime
```
Which then means double configuration of the configuration.

**Comment by jcvenegas** [comment]
So seems that both configs are being added when parsing   https://github.com/kata-containers/documentation/blob/master/install/docker/debian-docker-install.md#install-docker-for-kata-containers-on-debian

**Comment by grahamwhaley** [comment]
Ah, I see, thanks @jcvenegas - so, this is one of our 'magic' things where it actually runs the code fragments from the document, and that document says 'do either (a) or (b)', but of course, our script then runs both fragments!
@jodh-intel - I don't think the magic script has a method for choices does it, but, maybe we can use the old `sh` or `bash` code fragment annotation trick to only run one of them. Question is, which fragment would we prefer:
- traditionally we have done the systemd commandline edits
- but, the /etc/docker json file always feels cleaner and more obvious to me.

Any volunteers to raise the PR?

**Comment by jodh-intel** [comment]
Hmm, nobody else seems to have volunteered... so I'll pick this one up.
