### ISSUE TITLE
Missing curl dependency check in kata-manager.sh on Debian 9

### ISSUE THREAD

**Issue by olberger** [kata-containers/documentation#443]
I triggered an installation on fresh (rather minimal) install of Debian 9 and the script failed on missing curl.

I'm not sure there's a check for dependencies, but apparently curl wasn't in the list.

Hope this helps,

**Comment by grahamwhaley** [comment]
@olberger - looks like `kata-manager` tries to use `curl` and `wget`, and dies with a clear error if it cannot find either:
https://github.com/kata-containers/tests/blob/master/cmd/kata-manager/kata-manager.sh#L240-L254

Can you post the output you got?

**Comment by olberger** [comment]
I'll try to report of the precise error...

Let me add a detail, also. I reported this initially as it lead me to run the script twice, which may have induced #442.

AFAICS it may be better to perform the check in detect_downloader early enough (before get_git_repo) to avoid having done anything serious on the system's config. I.e. detect missing dependencies before installing or configuring anything... or maybe it's alreadly that way and I couldn't tell just by reading https://github.com/kata-containers/tests/blob/master/cmd/kata-manager/kata-manager.sh ;-)

Hope this helps.

**Comment by olberger** [comment]
The error I got is:
```
E: Sub-process returned an error code
/tmp/tmp.AcmeNORvsJ: line 36: curl: command not found
```
Looking at that script, it's:
```
Script auto-generated from '/root/go/src/github.com/kata-containers/documentation/install/debian-installation
-guide.md'
...
curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/Debian_${VERSION_ID}/Release.key | sudo apt-key add -
```
There you go ;-)

**Comment by jodh-intel** [comment]
Thanks @olberger - I'll look at this...

**Comment by jodh-intel** [comment]
@olberger - PR raised here: https://github.com/kata-containers/tests/pull/1503.

**Comment by olberger** [comment]
I probably should have mentioned I downloaded kata-manager script with wget and not curl, as I was embedding it inside a VM, so not strictly following instructions.

Also I am not so fond of volatile curl as in bash -c "$(curl ...).

Security-wise it is really bad habit to instruct users to do so (MitM, etc.)

**Comment by jodh-intel** [comment]
@olberger - as mentioned, you do not have to use that installation method. We offer five different alternatives:

- https://github.com/kata-containers/documentation/tree/master/install#installing-on-a-linux-system
