### ISSUE TITLE
kata-deploy does not work inside minikube

### ISSUE THREAD

**Issue by muellert** [kata-containers/documentation#448]
I am trying to follow these instructions:

https://github.com/kata-containers/documentation/blob/041fa7e61bb1aed39f6e3ea66deb08bfba98f79b/install/minikube-installation-guide.md

I get as far as:

$ kubectl apply -f kata-deploy.yaml
daemonset.apps/kata-deploy created

Inside minikube, the /opt/kata directory is being created, but remains empty.

$ hostname
minikube
$ pwd
/opt/kata
$ ls -al
total 0
drwxr-xr-x 2 root root 0 Apr 26 22:07 .
drwxr-xr-x 4 root root 0 Apr 26 22:07 ..
$ 

On the host:

$ minikube version
minikube version: v1.0.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**Comment by krsna1729** [comment]
@muellert post the logs of the kata-deploy pod in kube-system ns and `kubectl get node -owide --show-labels`

**Comment by grahamwhaley** [comment]
It can also take a short while (maybe a couple of minutes) for the deploy to complete and fill out the `/opt/kata/` tree. @krsna1729 - is there an easy way to check from `kubectl` if the deploy is still in flight or is complete?

**Comment by krsna1729** [comment]
@grahamwhaley  something like this in our script

`kubectl -n kube-system wait --timeout=1m --for=condition=Ready -l name=kata-deploy pod`

**Comment by grahamwhaley** [comment]
@krsna1729 - waiting on the pod created by the deployment and not the deployment itself - that sounds more feasible (as deployments do not set a Ready condition) - but, does that work for multi-node deploys @krsna1729 ?

**Comment by krsna1729** [comment]
yes. This waits for all pods with a particular label to ready. irrespective of the node. the only race i see is if they were not even created in etcd

**Comment by EmmEff** [comment]
Has there been any update on this? I am seeing the following:

```
ubuntu@ubuntusrv:~/packaging/kata-deploy$ k logs kata-deploy-jz7pl  -n kube-system
Error from server (Forbidden): leases.coordination.k8s.io "minikube" is forbidden: User "system:serviceaccount:kube-system:kata-label-node" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
ubuntu@ubuntusrv:~/packaging/kata-deploy$
```

minikube version: 1.6.2 running K8s v1.17.1 with kata containers 1.9.3

**Comment by grahamwhaley** [comment]
I've not seen that error before, but then I've also not spun up kata-deploy or minikube recently....
/cc @krsna1729 @egernst who may have more ideas.

**Comment by grahamwhaley** [comment]
@EmmEff - having said that, I was just trying to run up `minikube` with `kata-deploy`, and see this with minikube both versions 1.1.1 and 1.7.2 (latest).
I'll have a dig into this and try and figure out what has changed. @egernst , any ideas here - feels like maybe an rbac/perms type issue?

**Comment by grahamwhaley** [comment]
more info. I exec'd into the kata-deploy container, added a `set -x` to the kata-deploy.sh script and ran it...:

```bash
/opt/kata-artifacts/scripts/kata-deploy.sh install
+ set -o errexit
+ set -o pipefail
+ set -o nounset
+ crio_conf_file=/etc/crio/crio.conf
+ crio_conf_file_backup=/etc/crio/crio.conf.bak
+ containerd_conf_file=/etc/containerd/config.toml
+ containerd_conf_file_backup=/etc/containerd/config.toml.bak
+ shims=("fc" "nemu" "qemu" "qemu-virtiofs")
+ main install
++ id -u
+ euid=0
+ [[ 0 -ne 0 ]]
++ get_container_runtime
+++ kubectl describe node minikube
Error from server (Forbidden): leases.coordination.k8s.io "minikube" is forbidden: User "system:serviceaccount:kube-system:kata-label-node" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
```

So, looks like `kubectl` inside the pod no longer has the perms (by default?) to probe the stack. I'll keep looking to see if we need to add something to the yaml to grant further perms...

**Comment by grahamwhaley** [comment]
OK, this looks like it was already fixed in the code base in https://github.com/kata-containers/packaging/pull/844, and should have made it into the kata-deploy image in the dockerhub, but, we are tracking down why that seems to have not happened.

The fix was to move from using `kubectl describe node` to `kubectl get node`, which requires less permissions. It does look like some default permission has gotten stricter at some point.

A quick hack/fix is to edit the kata-deploy.yaml to use the tagged image version rather than the default 'current':

```patch
diff --git a/kata-deploy/kata-deploy/base/kata-deploy.yaml b/kata-deploy/kata-deploy/base/kata-deploy.yaml
index 9d47703..10c63a6 100644
--- a/kata-deploy/kata-deploy/base/kata-deploy.yaml
+++ b/kata-deploy/kata-deploy/base/kata-deploy.yaml
@@ -16,7 +16,7 @@ spec:
       serviceAccountName: kata-label-node
       containers:
       - name: kube-kata
-        image: katadocker/kata-deploy
+        image: katadocker/kata-deploy:1.10.0
         imagePullPolicy: Always
         lifecycle:
           preStop:
```

We'll update here once we have fixed the 'default' image etc.

**Comment by grahamwhaley** [comment]
OK, so, there is more than one bugg-ette... second one detailed over at https://github.com/kata-containers/packaging/issues/928
