### ISSUE TITLE
go-lint.sh is not exist

### ISSUE THREAD

**Issue by xiaoding945** [kata-containers/documentation#450]
when I follow the steps with https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#pull-requests.
however ,when I do "make check", I meet the problem such as follows:
![image](https://user-images.githubusercontent.com/19324666/56943027-38710f00-6b50-11e9-95cd-00335153c2ad.png)
I can,t find any same issue ,i can't find go-lint.sh too. I am hoping get your reply@jodh-intel

**Comment by jodh-intel** [comment]
Hi @xiaoding945 - thanks for raising!

That does indeed look like a small bug. `virtcontainers` *used* to live in a separate repository where that file does exist (https://github.com/containers/virtcontainers/blob/master/.ci/go-lint.sh).

I can understand the confusion - that doc should make it clear that it is only the `make` that needs to be run in the `virtcontainers` sub-directory. You actually need to run the `make check` and `make test` at the top level (our docs don't make that very clear), so you should try running like this:

```sh
$ cd $GOPATH/src/github.com/kata-containers/runtime
$ make check
```

(I'll update the doc...)

But also, I would recommend *NOT* running as `root` direclty - the golang tests will actually be run twice (once as your current user, and -- if you are not running as `root` -- once as `root` but using `sudo` for safety).

**Comment by jodh-intel** [comment]
Runtime issue fixed by https://github.com/kata-containers/runtime/pull/1610.

**Comment by jodh-intel** [comment]
Documentation fixed by https://github.com/kata-containers/community/pull/94.
