### ISSUE TITLE
docs: Fix broken link 

### ISSUE THREAD

**Issue by nitkon** [kata-containers/documentation#451]
https://github.com/kata-containers/documentation/blob/master/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md#how-to-use-kata-containers-and-cri-containerd-plugin-with-kubernetes

Broken Link: `containerd-shim-kata-v2 (short as shimv2 in this documentation) `

**Comment by jodh-intel** [comment]
@nitkon - is the fix you need included in https://github.com/kata-containers/documentation/pull/434? If not, I can add it if you provide details?

**Comment by nitkon** [comment]
@jodh-intel : The fix is in #434 . Will close this issue.
