### ISSUE TITLE
ubuntu16.04 restart docker  failed with runtime kata-runtime

### ISSUE THREAD

**Issue by SeekFlame** [kata-containers/documentation#465]
when i run “sudo systemctl restart docker”，have this problem，how i can deal with it。
**_****_**
root@master:/etc/systemd/system/docker.service.d# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─kata-containers.conf
   Active: failed (Result: start-limit-hit) since Fri 2019-05-10 14:18:11 CST; 10s ago
     Docs: https://docs.docker.com
  Process: 11881 ExecStart=/usr/bin/dockerd -D --add-runtime kata-runtime=/usr/bin/kata-runtime --default-runtime=kata-runtime (code=exited, status=1/FAILURE)
 Main PID: 11881 (code=exited, status=1/FAILURE)

May 10 14:18:09 master systemd[1]: docker.service: Unit entered failed state.
May 10 14:18:09 master systemd[1]: docker.service: Failed with result 'exit-code'.
May 10 14:18:11 master systemd[1]: docker.service: Service hold-off time over, scheduling restart.
May 10 14:18:11 master systemd[1]: Stopped Docker Application Container Engine.
May 10 14:18:11 master systemd[1]: docker.service: Start request repeated too quickly.
May 10 14:18:11 master systemd[1]: Failed to start Docker Application Container Engine.
May 10 14:18:11 master systemd[1]: docker.service: Unit entered failed state.
May 10 14:18:11 master systemd[1]: docker.service: Failed with result 'start-limit-hit'.

**Comment by SeekFlame** [comment]
the problem has dealed 
just modify the /etc/docker/daemon.json
rename as /etc/docker/daemon.conf

**Comment by grahamwhaley** [comment]
Thanks @SeekFlame for the update.
I suspect you ended up with `kata-runtime` configured both in `/etc/docker/*` and in `/etc/systemd/*`. Can I ask how you installed Kata? I have seen this before when somebody has installed using packages (rpm, deb) or by hand, and then installed using `kata-deploy`, as those methods use two (conflicting) ways to configure Kata into Docker.

thanks!
