### ISSUE TITLE
install: static: release tab points to page with no static instrs

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/documentation#470]
afaict, our static release balls on our [releases page](https://github.com/kata-containers/runtime/releases) point to our [docs repo install page](https://github.com/kata-containers/documentation/tree/master/install), but nowhere on that page does it say how to install the static binary ball?
I was looking at the v1.6.3 section on the release page.

Maybe I'm missing something?
/cc @egernst @jcvenegas

**Comment by jcvenegas** [comment]
@grahamwhaley we dont have documentation for that we should add it.
