### ISSUE TITLE
Add Annotations' documentation

### ISSUE THREAD

**Issue by shrmrf** [kata-containers/documentation#486]
**Which feature do you think can be improved?**

Docs. Annotations are available to be used ([see `annotations.go`](https://github.com/kata-containers/runtime/blob/master/virtcontainers/pkg/annotations/annotations.go)) but not documented.

**How can it be improved?**

By adding an `Annotations.md` file and linking to it from whereever applicable.

**Additional Information**

Maybe also create use-cases based on annotations (e.g. custom rootfs https://github.com/kata-containers/documentation/issues/294 )

**Before raising this feature request**

_Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?_\
Yeah, I doubt if it applies to this document.

**Comment by grahamwhaley** [comment]
@shrmrf - thanks for opening the issue!
As this is your first issue, and maybe leading to a PR, I'll make sure you've located the [kata documentation on how to open a PR](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#pull-requests) :-)

Oh, there is a docs guide as well at https://github.com/kata-containers/documentation/blob/master/Documentation-Requirements.md

As you note, I think the hard first step is deciding *where* to document this information. afaik, these annotations are k8s specific (i.e., there is no way to add them into a `docker` image or to a generic OCI image manager etc.). So, much though my head wants to start a 'configuration.md' docs file and document all about how to configure Kata, that would probably pertain directly to the runtime itself, and not to the k8s specific annotations.

@mcastelino has just been adding some more k8s annotations I believe - see https://github.com/kata-containers/runtime/issues/1655 and https://github.com/kata-containers/runtime/pull/1695. @mcastelino - I note that PR has no docs updates in it ;-) Shall we try to combine this Issue with your work, and decide where to annotate the (k8s specific only are they??) annotations for Kata?

I'm going to propose we add the annotations docs to the k8s document at:
https://github.com/kata-containers/documentation/blob/master/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md

Now, afaik that document already needs work (globally we need to unify all kata k8s docs into one I think and update some things - like removing the `trusted/untrusted` docs from that page and replacing them with `RuntimeClass`) - but - I think adding the annotations in now is fine - it is better than not having them documented anywhere!

I think the cleanest thing to do right now is to add a new section at the end of that document, something like:

----

## Configuration

### Per-pod annotations

and then probably have a table of all the annotations, and maybe a subsection for any annotations that need lengthy explanation.

----

@mcastelino - will this fit in with your annotations work? can you think of anywhere better to document them?
@egernst @ganeshmaharaj for thoughts on the k8s docs in general (I thought we had a plan to globally fix them, but I don't think we actually have an Issue for it do we? but, tbh, there seem to be less k8s docs now than there used to, which is good).
@jodh-intel for some docs-head in put :-)

**Comment by jodh-intel** [comment]
Thanks for raising @shrmrf!

The simplest approach would be to simply update `annotations.go` with a shed-load more comments and then link to the URL below from one of the `README.md`'s:

- https://godoc.org/github.com/kata-containers/runtime/virtcontainers/pkg/annotations

That approach would also reduce the likelihood of "doc-rot" since the doc would be with the code.

**Comment by grahamwhaley** [comment]
@jodh-intel , I think doing this via the auto code godoc path is an excellent idea.
Having a look at the godoc link for that file at present, it looks very variable/function centric. I've not looked into how flexible or not godoc is - but, do you know, is there a way to maybe extract all the annotations into a nice table onto that godoc page or similar? I think just having the annotations documented in a very go-code API style is not going to be awfully user friendly otherwise :-(

**Comment by jodh-intel** [comment]
godoc is pretty simple (https://blog.golang.org/godoc-documenting-go-code). However, it will extract all comments and present them in a sane fashion. It doesn't support embedded HTML and/or tables afaik.

Turning the problem round, we could auto-generate `annotations.go` from a YAML file and also generate markdown from it too (avec fancy tables). But that's an order of magnitude more work ;)

**Comment by cespo** [comment]
I'm pretty interested in this documentation
I'm trying to setup the number of `default_vcpus` and `default_max_vcpus` using the annotations but it doesn't work for me.
I'm currently running kata 1.9.1 and this is what I have in my pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: dind
  annotations:
    io.kata-containers.config.hypervisor.default_max_vcpus: "2"
    io.kata-containers.config.hypervisor.default_vcpus: "2" 
```

From the debug console I can see only 1 vCPU
```
root@aa3b01afa85b:/# cat /proc/cpuinfo | grep proc
processor	: 0
```

Anything I have to setup to enable this feature?

**Comment by shrmrf** [comment]
I never got around to contributing to the docs :thinking:  Really sorry... I _did_ get annotations working though and I wrote a post about it while we were discussing the best way to bring that _into_ the docs here properly...

These are more "notes to myself" than for everyone on the Internet: https://shrmrf.github.io/rants/kata-containers/k8s/linux/2019/06/11/Kata-annotations.html

You might find it useful @cespo until we have something in `master`. :man_shrugging:

**Comment by cespo** [comment]
Thanks for sharing that page @shrmrf 
For some reason annotations are not working for me.
Why did you use the `com.github.containers.virtcontainers` prefix?

**Comment by shrmrf** [comment]
yes, I think so... it's been some time since I last played around with annotations though.

**Comment by grahamwhaley** [comment]
Adding a note from a slack chat that I think is relevant:

```
@amshinde 
you will need additional configuration in your containerd config file :
[plugins.cri.containerd.runtimes.kata]
           runtime_type = "io.containerd.kata.v2"
           pod_annotations = ["io.kata-containers.*"]
actually make that pod_annotations = ["io.katacontainers.*"]
no - there
similarly in your pod yaml as well
```

/cc @amshinde @cespo ;-)

**Comment by devimc** [comment]
@cespo @grahamwhaley  kata containers annotations start with `io.katacontainers` not with `io.kata-containers`
https://github.com/kata-containers/runtime/blob/master/virtcontainers/pkg/annotations/annotations.go#L9
