### ISSUE TITLE
need to provide guidance on sandbox overhead

### ISSUE THREAD

**Issue by egernst** [kata-containers/documentation#490]
orchestrators should expect a pod created by Kata Containers to incur a non-negligible overhead on top of the container resource requests.

In Kubernetes, work is being done to formally register and apply this overhead.  See [PodOverhead KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node).

Related to the outstanding PR #428, we should introduce the concept and provide guidance for memory and CPU overhead of running a pod / container with Kata.

**Comment by gkhanna79** [comment]
CC @gkhanna79
