### ISSUE TITLE
FAQ page on the Kata Containers website displays only sample text

### ISSUE THREAD

**Issue by whalehub** [kata-containers/documentation#493]
https://katacontainers.io/faq/

![2019-06-11 10 19 37 katacontainers io abd5b31a801c](https://user-images.githubusercontent.com/44198148/59255450-69a22c00-8c32-11e9-954a-907b5817cae9.png)

**Comment by jodh-intel** [comment]
Hi @whalehub - thanks for reporting and ouch!

@jimmytipit / @ttx - could you alert those who maintain that site and see if we can get this issue fixed please?

**Comment by ttx** [comment]
Nice catch! Forwarded to web team

**Comment by jimmytipit** [comment]
Hi there. This page was not meant to be public, but I see it got crawled. It's not properly returning a 404.
