### ISSUE TITLE
Kata Containers is not the default runtime after installation

### ISSUE THREAD

**Issue by whalehub** [kata-containers/documentation#494]
# Description of problem

I installed Kata Containers on Debian 9 (Stretch) earlier today by following the instructions from the Wiki to a T but for some reason, it still isn't set as the default Docker runtime.

# Expected result

I expected the commands `docker inspect` and `docker info` to return `"Runtime": "kata"` and `Default Runtime: kata` respectively.

# Actual result

The commands `docker inspect` and `docker info` returned `"Runtime": "runc"` and `Default Runtime: runc` respectively.

**Comment by jodh-intel** [comment]
Hi @whalehub - thanks for raising. When you say "wiki" do you actually mean you installed from:

- https://github.com/kata-containers/documentation/blob/master/install/README.md

It sounds like you may have a conflict between the runtimes specified in one of these locations:

- `/etc/systemd/system/docker.service.d/kata-containers.conf`
- `/etc/default/docker`
- `/etc/docker/daemon.json`

See: https://github.com/kata-containers/documentation/blob/master/install/docker/debian-docker-install.md

**Comment by whalehub** [comment]
@jodh-intel I followed these instructions to install Kata Containers on Debian: https://github.com/kata-containers/documentation/blob/master/install/debian-installation-guide.md

Afterwards, I followed these instructions to set Kata Containers as the default Docker runtime in systemd: https://github.com/kata-containers/documentation/blob/master/install/docker/debian-docker-install.md

**Comment by jodh-intel** [comment]
Thanks @whalehub - sound you did a manual install by the sounds of it. Could you check the three files above and see which specify the Kata runtime?

**Comment by whalehub** [comment]
@jodh-intel Turns out that all that was needed was a simple reboot. The old IT adage "Have you tried turning it off and on again?" strikes again!

**Comment by jodh-intel** [comment]
@whalehub - hahaa! :smile:

You may have been able to just `sudo systemctl restart docker` but a reboot works I guess ;)

Glad it's working for you now though.

**Comment by whalehub** [comment]
@jodh-intel I'm afraid that `systemctl restart docker` didn't fix the issue - it took a full restart.
