### ISSUE TITLE
kata-runtime kata-check not success

### ISSUE THREAD

**Issue by fanux** [kata-containers/documentation#496]
```
ERRO[0000] kernel property not found                     arch=amd64 description="Host Support for Linux VM Sockets" name=vhost_vsock pid=23716 source=runtime type=module
WARN[0000] modprobe insert module failed: modprobe: ERROR: could not insert 'kvm_intel': Operation not supported
  arch=amd64 error="exit status 1" module=kvm_intel name=kata-runtime pid=23716 source=runtime
ERRO[0000] kernel property not found                     arch=amd64 description="Intel KVM" name=kvm_intel pid=23716 source=runtime type=module
ERRO[0000] kernel property not found                     arch=amd64 description="Host kernel accelerator for virtio" name=vhost pid=23716 source=runtime type=module
ERRO[0000] ERROR: System is not capable of running Kata Containers  arch=amd64 name=kata-runtime pid=23716 source=runtime
```

I think the install guide should provide some preinstall requirements

**Comment by jodh-intel** [comment]
Hi @fanux - thanks for raising. It is in fact surprisingly hard to list exhaustively all systems that can (or cannot) run Kata (we've tried in the past and there are always exceptions to the rules it seems). That is in fact why we introduced `kata-check`.

But maybe the rest of the team have thoughts on this?

**Comment by fanux** [comment]
For example, bios enable virulization.
```
[root@helix105 ~]# modprobe kvm-intel
modprobe: ERROR: could not insert 'kvm_intel': Operation not supported
[root@helix105 ~]# dmesg |grep kvm
[    8.239309] kvm: disabled by bios
```

**Comment by yanzmgit** [comment]
I have the similar problem.

> kata-runtime kata-check
> ERRO[0000] CPU property not found                        arch=amd64 description="Virtualization support" name=vmx pid=19960 source=runtime type=flag
> WARN[0000] modprobe insert module failed: modprobe: ERROR: could not insert 'kvm_intel': Operation not supported
>   arch=amd64 error="exit status 1" module=kvm_intel name=kata-runtime pid=19960 source=runtime
> ERRO[0000] kernel property not found                     arch=amd64 description="Intel KVM" name=kvm_intel pid=19960 source=runtime type=module
> ERRO[0000] ERROR: System is not capable of running Kata Containers  arch=amd64 name=kata-runtime pid=19960 source=runtime

I know the reason is that  kata containers need kvm support. 
But I suggest that  could the can also kata containers also support new type(qemu-kvm)  just like the virsh dose ?  for example:

> virt-install  --virt-type=kvm  
 create a kvm instance which need hardware support.
 
>virt-install --virt-type=qemu 
 create a qumu-kvm instance which dont need real hardware support.

The reason is that many dockerd is running on virtaul machine, and generally those machines dont support kvm as kata containers require.

**Comment by grahamwhaley** [comment]
Given one of the main reason for Kata is to use hardware virtualisation as an extra security layer, allowing kata to run with 'soft' virtualisation has never been on the roadmap. I think it might introduce other issues as well, like a major performance hit.
I could see that maybe this could be a developer/debug option where somebody wants to try out kata on a system that does not have hardware acceleration, but, it sounds like a pretty special case to me. And, we've been trying to reduce the number of config options Kata has to simplify setup and install, so adding another rarely-used option may not be high up the list of priorities.

**Comment by yanzmgit** [comment]
> Given one of the main reason for Kata is to use hardware virtualisation as an extra security layer, allowing kata to run with 'soft' virtualisation has never been on the roadmap. I think it might introduce other issues as well, like a major performance hit.
> I could see that maybe this could be a developer/debug option where somebody wants to try out kata on a system that does not have hardware acceleration, but, it sounds like a pretty special case to me. And, we've been trying to reduce the number of config options Kata has to simplify setup and install, so adding another rarely-used option may not be high up the list of priorities.


Thanks. Got that.
