### ISSUE TITLE
dev docs, need updating for initrd and qemu?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/documentation#51]
I think https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#build-and-install-the-kata-containers-runtime may be out of date due to a couple of recent changes:
- the toml config file now has a line for an initrd.img, which is not built and installed by this doc - so kata-runtime fails to load the toml (as the file is not found, which is an error) (a quick fix is to just hand comment out the initrd img line in the toml)
- the toml config file now referes to the system qemu (not the lite version), but on some distros (my Ubuntu machine for instance), the system qemu is old (2.5.0), and does not have the necessary nvdimm options, so errors out. (a quick fix is to update the toml by hand to point back at the lite qemu)

**Comment by grahamwhaley** [comment]
@devimc @bergwolf - do you concur?
If so, I might find time to fix and test the doc...

**Comment by bergwolf** [comment]
@grahamwhaley the initrd part is handled in #45. Please help to review and  merge if that's OK to you.

**Comment by GabyCT** [comment]
Closing this issue as the `initrd` documentation was already merged

**Comment by amshinde** [comment]
This has gone stale. Closing.
