### ISSUE TITLE
Add documentation for rootless kata containers with podman

### ISSUE THREAD

**Issue by gabibeyer** [kata-containers/documentation#540]

**Comment by eadamsintel** [comment]
I should note that I eventually got this to work on Clear Linux but I had to manually compile and install podman, slirp4netns, add a /etc/hosts file, and change permissions.  I had issues on Friday with this working with /etc/shadow and being out of subuid, subgid. I couldn't get the `./configure` for the shadow-maint repo to finish but I am not sure I needed that anyways.  I think rebooting this morning fixed the problem but everything I did on Friday is a bit fuzzy.  Regardless, the instructions gave me enough clues to get this to work on Clear Linux but I am not 100% everything I did was necessary.  I might reflash and try again.
