### ISSUE TITLE
Wiki UserGuide Memory allocation link wrong

### ISSUE THREAD

**Issue by JackKuo-tw** [kata-containers/documentation#546]
# Description of problem

The link of "2048 MiB" in [UserGuide > memory allocation](https://github.com/kata-containers/documentation/wiki/UserGuide#memory-allocation) is wrong.
The old Makefile of DEFMEMSZ was at line 146.
But now is 153.

# Expected result

https://github.com/kata-containers/runtime/blob/master/Makefile#L153

# Actual result

https://github.com/kata-containers/runtime/blob/master/Makefile#L146

**Comment by caoruidong** [comment]
Thanks for raising. Just fix it.

**Comment by grahamwhaley** [comment]
thanks both - yeah, fixed file links are just going to go stale over time :-(, but I don't think there is any way to do anchored relative links to a source file - we'd have to make it a descriptive paragraph to make it 'futureproof'...

**Comment by JackKuo-tw** [comment]
The [permanent link method](https://help.github.com/en/articles/creating-a-permanent-link-to-a-code-snippet) seems to be a not bad solution.
And the link of that line should be:
https://github.com/kata-containers/runtime/blob/a1e0a4c3f5c3fa2a430536ac7974769600afcb07/Makefile#L153

**Comment by GabyCT** [comment]
This issue has been fixed, closing this issue
