### ISSUE TITLE
Update dev guide to explain how to build a custom kernel

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#55]
Once https://github.com/kata-containers/packaging/issues/1 lands, we should have some tooling to make it easy to create a custom kernel based on the base Kata kernel configuration.

**Comment by mcgrof** [comment]
issue#1 is now closed, are there some test branches with this custom kernel tooling?

**Comment by jodh-intel** [comment]
Hi @mcgrof - well, it's not technically closed yet, but I agree that I believe we've actioned it now ;)

@jcvenegas has added packaging tools for custom kernels here: https://github.com/kata-containers/packaging/tree/master/kernel so we should be able to get someone working on this issue.

There are still a lot of questions around handling kernel configs generally though. See:

- https://github.com/kata-containers/packaging/issues/8
- https://github.com/kata-containers/packaging/issues/55
- https://github.com/kata-containers/packaging/issues/56
