### ISSUE TITLE
[Questions] If /etc/docker/daemon.json is required

### ISSUE THREAD

**Issue by zhanggbj** [kata-containers/documentation#550]
# Description of problem

**Env**: baremetal, ubuntu 18.04
Followed [Install Docker for Kata Containers on Ubuntu](https://github.com/kata-containers/documentation/blob/master/install/docker/ubuntu-docker-install.md#install-docker-for-kata-containers-on-ubuntu) and added `/etc/docker/daemon.json`, docker failed to start with an error below.

```
root@openshift-grace:~/workspace/zhanggong# systemctl status docker.service
* docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           `-kata-containers.conf
   Active: inactive (dead) (Result: exit-code) since Tue 2019-09-03 03:26:08 CDT; 2ms ago
     Docs: https://docs.docker.com
  Process: 20228 ExecStart=/usr/bin/dockerd -D --add-runtime kata-runtime=/usr/bin/kata-runtime --default-runtime=kata-runtime (code=exited, status=1/FAILURE)
 Main PID: 20228 (code=exited, status=1/FAILURE)

Sep 03 03:26:08 openshift-grace systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Sep 03 03:26:08 openshift-grace systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Sep 03 03:26:08 openshift-grace systemd[1]: Stopped Docker Application Container Engine.
Sep 03 03:26:08 openshift-grace systemd[1]: docker.service: Start request repeated too quickly.
Sep 03 03:26:08 openshift-grace systemd[1]: docker.service: Failed with result 'exit-code'.
Sep 03 03:26:08 openshift-grace systemd[1]: Failed to start Docker Application Container Engine.
```

If without `/etc/docker/daemon.json` and start docker, it looks like docker is using kata-container runtime as below,  the kernal version is differnt.
```
root@openshift-grace:~/workspace/zhanggong# docker run busybox uname -a
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
ee153a04d683: Pull complete
Digest: sha256:9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70
Status: Downloaded newer image for busybox:latest
Linux f4a01036f446 4.19.52-35.container #1 SMP Wed Jul 24 16:44:14 UTC 2019 x86_64 GNU/Linux

root@openshift-grace:~/workspace/zhanggong# uname -a
Linux openshift-grace 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

SO does `/etc/docker/daemon.json` is required?

# Expected result

Docker can start successfully following the instructions.

# Actual result

Docker failed to start following the instructions.

**Comment by zhanggbj** [comment]
In a similar issue, someone also mentioned he removed `/etc/docker/daemon.json` and it works. https://github.com/kata-containers/runtime/issues/645#issuecomment-449032774

**Comment by caoruidong** [comment]
If you already config kata as default runtime, daemon.json is not required. It seems your file may has some format error.

**Comment by zhanggbj** [comment]
@caoruidong 
So far if I do `docker info | grep Runtime` I can get kata runtime, and I think it is configured in steps as below. So it is true that `/etc/docker/daemon.json` is not necessary? Just want to double confirm the env is configged correctly without this step. Thx!
```
$ cat <<EOF | sudo tee /etc/systemd/system/docker.service.d/kata-containers.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -D --add-runtime kata-runtime=/usr/bin/kata-runtime --default-runtime=kata-runtime
EOF
```

**Comment by caoruidong** [comment]
I think it is probably because daemon.json and systemd config file are overlapped, so it gets error. If you have nothing else to config, daemon.json is not necessary.

**Comment by jodh-intel** [comment]
@zhanggbj - @caoruidong is correct - you don't need `/etc/docker/daemon.json` if you installed Kata using the [automatic method](https://github.com/kata-containers/documentation/tree/master/install#packaged-installation-methods). That is why the document says:

> Configure Docker to use Kata Containers by default with **one** of the following methods:

Installing using the automatic method will create a working system - you don't need to do anything else. This is because the automatic method selects option `i systemd` and creates `/etc/systemd/system/docker.service.d/kata-containers.conf` for you.

However, I agree that this is unclear in the installation documents so I've raised https://github.com/kata-containers/documentation/pull/552 to attempt to resolve this issue.

**Comment by zhanggbj** [comment]
@jodh-intel 
Thanks for fixing it!

**Comment by jodh-intel** [comment]
Hi @zhanggbj  - no problem! Can we close this issue now?
