### ISSUE TITLE
Update list of hypervisors in architecture doc

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#567]
As mentioned in https://github.com/kata-containers/documentation/issues/566, the list of supported hypervisors in the architecture doc is (now) incomplete.

**Comment by egernst** [comment]
Let's go ahead and create a new hypervisor document, highlighting what devices are leveraged per VMM, as well.  This will help create a more cohesive story, and hopefully help end users with deciding which VMM or hypervisor works best for them.
