### ISSUE TITLE
Create installation documentation

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#57]
Once https://github.com/kata-containers/packaging/issues/1 is resolved and we have OBS packages, we need instructions for all distros we produce packages for.

**Comment by egernst** [comment]
Installation docs available for our packages (fedora, ubuntu): https://github.com/kata-containers/documentation/blob/master/install/ubuntu-installation-guide.md
https://github.com/kata-containers/documentation/blob/master/install/fedora-installation-guide.md
