### ISSUE TITLE
/ root directory readonly

### ISSUE THREAD

**Issue by Kvasscn** [kata-containers/documentation#573]
When i did a test with kata container, i found the kata vm /  root dir is readonly,  and  i had to  remount / with "rw" option at the console.
I didn't know why to set vm  / directory readonly, and is it possible  to set it writeable when kata vm startup?

**Comment by grahamwhaley** [comment]
@Kvasscn - can you give us some of your setup details?
Which version are you using. What is your kata config - are you using the 'factory' mode, which hypervisor are you using etc.?
This question may be better opened on the runtime repo (but we can carry on here...).

I think if you are using the `factory` mode, then it may be mounted `ro` - see https://github.com/kata-containers/runtime/blob/master/cli/config/configuration-qemu.toml.in#L249

/cc @gnawux @devimc for more thoughts.

**Comment by devimc** [comment]
@Kvasscn `/` is mounted as read-only for security reasons, since the same rootfs image is used to start all kata containers, nobody should modify it.  afaik it's not possible to re-mount it as rw at boot time

**Comment by Kvasscn** [comment]
Thanks for the reply. The kata version i used  is 1.9.0 rc0, and hypervisor is qemu. Because i need to run an additional daemon in kata vm, and the daemon program will create temproary files in /var dir, so i have to set the vm / root path writeable. I found that  setting kernel_params = "rw"  in kata configuration.toml  can achieve this purpose,  but not sure whether there are some hidden problems.

**Comment by Kvasscn** [comment]
An intresting things is though the / directory become writeable, and then i mkdir in the / path, after kata vm stoped  i  find the md5sum of kata rootfs image is  not changed. Once kata vm start again,  the temporary directory last created does not  exist (this is acceptable), does it due to kata  rootfs image being used as memory-backend-file and nvdimm device when qemu running?

**Comment by devimc** [comment]
backend-file is not modified because of the "share" flag, 

> "share=off", then guest writes won't be applied to the backend file and thus will be invisible to other guests.

afaik there are no hidden problems if you use "rw"

**Comment by Kvasscn** [comment]
@devimc  ok, thanks. 👍
