### ISSUE TITLE
Install Guest Kernel Images section needs location of clear-container vmlinux/vmlinuz

### ISSUE THREAD

**Issue by swsyes** [kata-containers/documentation#6]
The "Install Guest Kernel Images" section of the document is missing a pointer to the location wherefrom the user should fetch the "vmlinux.container" and "vmlinuz.container" images.

**Comment by egernst** [comment]
Looks like that section assumes you have Clear Containers already installed on the system. See github.com/clearcontainers/runtime and let me know if you run into any further issues.

**Comment by swsyes** [comment]
ok thanks. Will try and report. Will also try to edit / add the resulting method to the write-up.

**Comment by jodh-intel** [comment]
Hi @swsyes - thanks for reporting! Apologies for the oversight. I've now updated the wiki page with details of how to install the `linux-container` package:

- https://github.com/kata-containers/documentation/wiki/Developer-Guide/_compare/8be00444138518f43dffa7ec35ec57ad5ee9ff9c...ae20bfc73778ae3c499522d4cf437cdafe220883

Please do let us know here if this works for you.

**Comment by swsyes** [comment]
@jodh-intel Thanks! Is the Wiki editable by contributors? Do you take pull-requests for the same. Would like to help in the future.

**Comment by jodh-intel** [comment]
@swsyes - I _think_ the wiki should be editable by contributors, but please shout if you can't change it. If that's the case, we'll try to allow edits, but if that doesn't work out, you can certainly raise a PR and I'll update the doc on your behalf.

btw, the eventual plan is to move that wiki page "in-tree" (and then put a link from the wiki to the in-tree version to avoid breaking folk).
