### ISSUE TITLE
Improvements for release documentation

### ISSUE THREAD

**Issue by amshinde** [kata-containers/documentation#600]
Our release documentation has gotten a bit stale and needs updating. Some of the issues I have identified:
- [x] Update release cadence and add description about alpha releases/release candidate in Stable-Branch-Strategy.md. (https://github.com/kata-containers/documentation/issues/598)
- [ ] Releases.md has gotten stale and needs to be revisited, perhaps combined with Stable-Branch-Strategy.md 
Releases.md (https://github.com/kata-containers/documentation/blob/master/Releases.md) has a release checklist that certainly needs an update.
- [ ]  We need to add documentation about release process using github actions.

**Comment by amshinde** [comment]
cc @jodh-intel @egernst

**Comment by jeremiah** [comment]
Release documentation produces a dependency problem on Debian 10 Buster;

```
The following packages have unmet dependencies:
 kata-runtime : Depends: qemu-vanilla (= 4.1.1+git.99c5874a9b-46) but 4.1.0+git.9e06029aea-45 is to be installed
E: Unable to correct problems, you have held broken packages.
```
This error prevents me from installing the kata container runtime and other binaries, like shim.

**Comment by grahamwhaley** [comment]
@amshinde @jcvenegas - is this the package build issue that got fixed yesterday?

**Comment by jodh-intel** [comment]
Hi @jeremiah - I've just installed on a Debian 10.3.0 system using https://github.com/kata-containers/documentation/blob/master/install/installing-with-kata-manager.md#full-installation with no issues.

Please could you raise a bug at https://github.com/kata-containers/packaging/issues/new including as much detail as you can on the problem.

Ironically, the `kata-runtime` package contains a problem determination script (https://github.com/kata-containers/runtime/blob/master/data/kata-collect-data.sh.in as `/usr/bin/kata-collect-data.sh`) but that won't be installed for you. You can build and run it though easily:

```sh
$ git clone https://github.com/kata-containers/runtime
$ cd runtime
$ make data/kata-collect-data.sh
$ sudo sh data/kata-collect-data.sh > /tmp/data.md
```

**Comment by jeremiah** [comment]
Thank you @jodh-intel! I will follow the instructions you provided!

**Comment by amshinde** [comment]
@jeremiah We had seen the issue you mentioned, but have fixed it since then. Let us know if you are still seeing issues.

**Comment by jeremiah** [comment]
I hope to work on my installation today, thanks all for the response.

**Comment by jeremiah** [comment]
I installed kata-manager and everything installed fine but I couldn't restart docker. Trying to start the docker daemon manually gave me some useful output, the journal was vague and unhelpful. This was the error;
`
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: default-runtime: (from flag: kata-runtime, from file: kata-runtime)
`
/etc/docker/daemon.json was removed and then Docker restarted successfully. I don't think your install process installs that file, though I'm not 100% sure, in any case, it causes problems. :-)

**Comment by grahamwhaley** [comment]
@jeremiah - indeed, docker (understandably) won't accept conflicting settings coming from both the config file and the command line. iirc, our installer is only smart enough to edit one of them, and if the other already has settings in it, there can be a conflict :-(

@amshinde - just want to check, should this issue be closed, as I think the original entry covered a few document updates, not all of which are 'ticked'.

**Comment by amshinde** [comment]
@grahamwhaley All are ticked now :)
