### ISSUE TITLE
Any docs about katashared filesystem?

### ISSUE THREAD

**Issue by YongHaoWu** [kata-containers/documentation#606]
**Which feature do you think can be improved?**

Want a detail doc about katashared filesystem.

**Comment by grahamwhaley** [comment]
Hi @YongHaoWu - could you provide us a few more details? Are you meaning how Kata maps mounts and volumes from the host into the guest for instance? The [only specific mention](https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_agent.go#L62) of `katashared` in the code base is in the kata agent code that handles those mounts I believe.

I think I agree though, a nice short-ish document explaining and showing how the different container volume/mount types are handled and mapped into kata would be nice. I don't think we currently have that info in one clear place.

**Comment by YongHaoWu** [comment]
@grahamwhaley  Aha, I see. Yeah, I want to know how the different container volume/mount types are handled and mapped into kata .

Thanks.
