### ISSUE TITLE
Install: kata-runtime installation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by Xiaohua-Shen** [kata-containers/documentation#625]
# Description of problem

My system:
```
4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
execute below scripts
```
ARCH=$(arch)
BRANCH=stable-1.9
sh -c "echo 'deb http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/kata-containers.list"
curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/Release.key | apt-key add -
apt-get update
apt-get -y install kata-runtime kata-proxy kata-shim
```

# Expected result

about a weeks ago, it works, but now it doesn't work.

# Actual result

the error I faced:
```
root@kube:/# apt-get -y install kata-runtime kata-proxy kata-shim
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kata-runtime : Depends: kata-linux-container (= 4.19.75.69-10) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
seems it depends on kata-linux-container (= 4.19.75.69-10), but in the repository it has kata-linux-container (= 4.19.75.55-9)

**Comment by grahamwhaley** [comment]
@jcvenegas - do we know of any recent packaging glitches that might have caused this?

**Comment by Xiaohua-Shen** [comment]
I saw an old similar issue https://github.com/kata-containers/documentation/issues/485,

@grahamwhaley @jcvenegas can it be fix with similar ways?

**Comment by jodh-intel** [comment]
Confirmed. Installed latest / `master` is fine, as is `stable-1.10`, but `stable-1.9` fails as shown.

I've raised https://github.com/kata-containers/documentation/issues/629 as we need to have an explicit test for the last "*n*" supported stable branches.

**Comment by GabyCT** [comment]
I created a test to do the installation of OBS packages but it is running to use the latest master...I never tried with the branches https://github.com/kata-containers/packaging/blob/master/tests/run_obs_testing.sh and what this test is the installation of the packages and it runs a `kata-runtime kata-env`

**Comment by ariel-adam** [comment]
This is an old kernel release (4.19) and the issue doesn't happen in latest guest kernel.

**Comment by jodh-intel** [comment]
Closing - feel free to reopen if you hit this issue in newer versions of stable releases...
