### ISSUE TITLE
Correct README for trademarks, attribution, and resolve target users (role).  

### ISSUE THREAD

**Issue by mvincerx** [kata-containers/documentation#628]
**Which feature do you think can be improved?**

Correct [README](https://github.com/kata-containers/documentation/blob/master/README.md) for editorial review and determine its place in the hierarchy of mulitple Getting Started documents. Resolve target user(s) for which this doc is intended.   

For example, [Getting Started](https://github.com/kata-containers/documentation/blob/master/README.md#getting-started)  > Installation Guides appears to be biased toward a Go Developer.  This decision needs to be reconsidered in light of larger issues that remain unresolved: 

- How/Are the 7 primary contributors guided to quickly learn where to start?
- Why is a Go Developer the privileged user for Getting Started here?

*Note: The above questions are one question, stated in different ways.* 

**How can it be improved?**

- [ ] Improve user nav: Determine this document's place within the hierarchy of documentation and revise accordingly, given the "Additional information" stated here: https://github.com/kata-containers/community/issues/150.  

- Refer also to discussion here: https://github.com/kata-containers/documentation/issues/247

- [ ] Correct content for proper trademark, attributions, and logical flow. 

**Additional Information**

NA

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?
Yes

**Comment by jodh-intel** [comment]
Thanks @mvincerx ! I was thinking - you could always use an org-level GitHub project if you want to track work items across the different Kata repos for this doc improvement project?

- https://github.com/orgs/kata-containers/projects

**Comment by mvincerx** [comment]
> Thanks @mvincerx ! I was thinking - you could always use an org-level GitHub project if you want to track work items across the different Kata repos for this doc improvement project?

Yes. That was my thought too. I'll take that as an AR share with the project with you later this week. 

> * https://github.com/orgs/kata-containers/projects

**Comment by DougTW** [comment]
Starting review.

**Comment by jodh-intel** [comment]
Hi @mvincerx - I know you've super busy, but any update on this?

**Comment by jodh-intel** [comment]
Hi @DougTW - any update on this?
