### ISSUE TITLE
Test installation of stable OBS packages

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#629]
See: https://github.com/kata-containers/documentation/issues/625.

I think the simplest solution is to update the `kata-manager` script to accept an optional branch name so that if you wanted to install a specific branch version of Kata, you could run, say:

```
$ bash -c "$(curl -fsSL https://raw.githubusercontent.com/kata-containers/tests/master/cmd/kata-manager/kata-manager.sh) install-docker-system stable-1.10"
```
(see https://github.com/kata-containers/documentation/blob/master/install/installing-with-kata-manager.md#full-installation)

The default should remain `master`.

We can then update the test below to test `master`,  and the last 2-3 stable branches:

- https://github.com/kata-containers/documentation/blob/master/.ci/test-install-docs.sh

**Comment by cmaf** [comment]
@jodh-intel I'll look into it

**Comment by jcvenegas** [comment]
@jodh-intel  thanks for confirm, @grahamwhaley  I was not aware recent release was driven by @bergwolf probably he has more information

**Comment by jcvenegas** [comment]
actually looking to https://build.opensuse.org/package/show/home:katacontainers:releases:x86_64:stable-1.9/linux-container seems that actually the build was broken due to problems getting the new tarball for the kernel, I restarted the services from OBS to see if that helps

**Comment by amshinde** [comment]
@jcvenegas Thanks, just checked and seeing this error on
https://build.opensuse.org/package/show/home:katacontainers:releases:x86_64:stable-1.9/linux-container

```
Files could not be expanded: service error: Running /usr/lib/obs/service//download_url --protocol https --host cdn.kernel.org --path /pub/linux/kernel/v5.x/linux-4.19.75.tar.xz --outdir /var/cache/obs/cI9aRdTaTjKP/out more info
```
Looks like kernel 4.19 is being downloaded with  "v5.x" in its path, which does not seem right.
Can you take a look. cc @chavafg 

Going forward, I also think, the status for whether the packages have been generated and tested should be visible and easily accessible when we make a release similar to github build status badge maybe, so that we can mark a release as complete. 
(Does azure pipeline support this?)

**Comment by chavafg** [comment]
In addition, other users have reported in https://github.com/kata-containers/runtime/issues/2574#issuecomment-606147304 that latest alpha1 is not in [OBS master directory](http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_18.04/), which currently has the alpha0 release. The alpha1 packages can be found in [alpha directory](http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_18.04/). 
Seems confusing to me, is this correct? 
And do we have documentation about the different directories (master, head, alpha) in OBS?

**Comment by jcvenegas** [comment]
@amshinde I fixed the packages manually still need to to package testing, I found that the packaging tag for 1.9.6 was in master and not in the stable branch. @bergwolf did you had any issue with tagging with the script? Or probably was done the tagging by hand. Feel free to open an issue if you found something wrong.
@chavafg  I started both jobs for packages againg 1.9 and master to get it in the correct place.

**Comment by cmaf** [comment]
@jodh-intel Is your original suggestion still relevant?

**Comment by jodh-intel** [comment]
@cmaf - yes, I think so. Once we can run `kata-manager.sh` specifying a branch/release, we can automate testing the last 'n' stable releases in Azure/Jenkins/whatever.

**Comment by jodh-intel** [comment]
Nice! Now that @cmaf's https://github.com/kata-containers/tests/pull/2446 has landed, we can create a test in this repo I think to test the both `master` and the last "s" stable releases (where `s=2` - see https://github.com/kata-containers/documentation/blob/master/Stable-Branch-Strategy.md#branch-management).

The question is which approach do we take to convert this into a test?

a) Create `s * d` [Jenkins jobs](https://github.com/kata-containers/ci/tree/master/jenkins/jobs), one for each stable branch we want to perform install tests for (where `s` is the number of stable branches and `d` is the number of different distro versions we use in our CI).

b) Create `d` [Jenkins jobs](https://github.com/kata-containers/ci/tree/master/jenkins/jobs), where `d` is the number of different distro versions we use in our CI, and make the 9documentation repo CI test](https://github.com/kata-containers/documentation/blob/master/.ci/test-install-docs.sh) do the following:
   - Determine the list of stable releases to run the tests for.

     This is going to require a small amount of manual intervention, but I'd suggest we use a YAML database like this:

   ```yaml
    supported-branches:
      - master
      - stable-1.11
      - stable-1.10
   ```

   > **Note:** the CI script should always query the version of this file from the `master` branch.

   - Run the install tests for `master` plus each of the last `s` stable branches from the database above.

___

I prefer option (b) since:

- There is less crazy-mad Jenkins XML hacking involved.
- It almost maintains itself - we just need to update `supported-branches.yaml`.

And once we have a `supported-branches.yaml` database in this repo, we can hook it into all sorts of other interesting areas such as:

- [Our release process](https://github.com/kata-containers/documentation/blob/master/Release-Process.md).

  We do need to think carefully about OBS though - how are we going to make the docs CI test pull binary packages from OBS *before* we've officially announced a release? Do we use a staging area on OBS that the docs can pull from? But if so, the install docs would be incorrect when we announce the release. Sounds like we may need another variable in the install docs in addition to `BRANCH` possible? /cc @jcvenegas.

  When we create a new stable branch, we add it to the YAML file, and delete the oldest stable branch from it.

- The [stable branch strategy doc](https://github.com/kata-containers/documentation/blob/master/Stable-Branch-Strategy.md).

- OBS packaging.

/cc @amshinde, @gnawux, @grahamwhaley, @jcvenegas.

**Comment by cmaf** [comment]
@jodh-intel in option (b), would [test_install_docs.sh](https://github.com/kata-containers/documentation/blob/master/.ci/test-install-docs.sh) test the installation of all 3 branches in 1 vm or container instance? (using the remove-packages or remove-docker-system option)

**Comment by jodh-intel** [comment]
Hi @cmaf - option (b) would test for example `master`, `stable-1.11` and `stable-1.10` in a single Jenkins VM "node", yes. That script would installing a version of Kata, test it, then remove it before installing the next version. We'd need to ensure that `/etc/kata-containers/` doesn't exist before the tests to ensure we're only testing with the packaged configuration (`/usr/share/defaults/kata-containers/`).

What we do need to ensure though is that we have a Jenkins job for the documentation repo for each distro version we provide an install guide for. Looking at http://jenkins.katacontainers.io/, we currently have atleast one version [1] of:

- Ubuntu
- Fedora
- OpenSUSE
- CentOS

But we don't have the following:

- debian
- RHEL
- SLES

This raises the issue of our CI resources again. If there are any community folk who could help us out by providing CI resources for distros / distro versions they care about, please do get in touch!!

---

[1] - Ideally, we'd have two versions in most instances: the latest LTS version (if applicable) plus the latest version (if different). But for distro versions without an LTS version, the last two supported versions would make sense (so CentOS 7 + 8).

**Comment by cmaf** [comment]
@jodh-intel Ok, in that case, I ran into some problems (such as broken packages on Ubuntu, and not properly downgrading on CentOS) using `kata-manager.sh` uninstalling and reinstalling packages, both in increasing and decreasing order. 

Some of it can probably be handled in `cmd_remove_packages` like using autoremove. Otherwise, using `downgrade` or installing in increasing order.

**Comment by jodh-intel** [comment]
@cmaf - ah - sorry, I should have been clearer. I don't think these tests should be testing upgrade / downgrade (atleast at this stage). W should install each version, perform a basic test to ensure it "works", then totally remove all traces of it before installing the next version. Essentially do something like the following in pseudo-code:

```sh
for version in master stable-1.10 stable-1.9
do
    # also removes qemu packages
    remove_kata_packages()

    # removes /etc/kata-containers/
    delete_old_config()

    install_and_test_kata_version("$version")
done
```

If the kata manager script isn't correctly cleaning up, that's obviously a bug. We do need to be careful with that script given it's run by users for the automated install.

**Comment by jcvenegas** [comment]
@chavafg I vote for the second option

**Comment by jodh-intel** [comment]
I guess I'd vote for option (2) as it avoids constant Jenkins updates. But although I like the idea of automatically determining the previous set of stable branches, I worry slightly that something "odd" may happen to cause it to silently fail. For example, if a new strangely named stable branch was created (even by mistake), we may end up testing that rather than the correct one, giving a false sense of security. Hence, although both these options introduce a small amount of human interaction, I think we should do one of:

- Require a manual update to the `supported-branches.yaml ` file.

  I say "manual", but maybe "explicit" would be a better word: it could be updated automatically as part of the tooling we have to create a release. But atleast doing it that way, we've stated explicitly which branches/tags we consider to be stable releases. And anyone (or any other tool) can go and inspect that list.

- Use @jcvenegas's magic method, but require the CI to mail the publish those test results somehow / somewhere and also require that we get a human to check those results before announcing a release (again, to ensure there are no mistakes).

I'd vote for the 1st option above personally.

**Comment by jodh-intel** [comment]
Closing this since:

- The focus is now on [Kata 2.x](https://github.com/kata-containers/kata-containers).
- We are no longer producing OBS packages for Kata 2.x.
- Most distros are now producing their own Kata packages, which reduces the importance of this issue:

  https://github.com/kata-containers/kata-containers/tree/2.0-dev/docs/install#official-packages
