### ISSUE TITLE
Install problem on ubuntu 18.04 (gpg: no valid OpenPGP data found)

### ISSUE THREAD

**Issue by yrkim1018** [kata-containers/documentation#630]
Hi, 
I tried to install kata container according to the manual in git, but I cant't.
I did following things. 

--Install manual in git--
$ ARCH=$(arch)
$ BRANCH="${BRANCH:-master}"
$ sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/ /' > /etc/apt/sources.list.d/kata-containers.list"
_**$ curl -sL  http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -  -> problem occurs!!**_ 
$ sudo -E apt-get update
$ sudo -E apt-get -y install kata-runtime kata-proxy kata-shim

I checked Release key and found that "Resource is no longer available!" is written in it. 
How can I install a Kata?  

Please give me a help. Thanks.

**Comment by jodh-intel** [comment]
Hi @yrkim1018 - thanks for raising this!

Please can you provide more details:

- What distro and distro version you are running.
- What error you got (the exact message).
- Confirm which install method you used ("automatic" from https://github.com/kata-containers/documentation/tree/master/install#packaged-installation-methods ?)

I'll take a guess though. I suspect you are running Ubuntu 19.10 (Eoan)? As shown below, we are not producing packages for that version of Ubuntu currently:

http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/
(@GabyCT - do you have an update on that? I thought there was an issue to add 19.10 but can't find it...?)

However, this shouldn't be a "blocker" for you as you can install Kata using snap:

- https://github.com/kata-containers/documentation/blob/master/install/snap-installation-guide.md

**Comment by yrkim1018** [comment]
I solved with snap. Thank you for reply!
