### ISSUE TITLE
doc: add rate limiter annotations

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/documentation#681]
Hi guys

With https://github.com/kata-containers/kata-containers/pull/312 got merged, we need to add related docs here.

Add doc for tx/rx rate limiter annotations, that is, `io.katacontainers.config.hypervisor.rx_rate_limiter_max_rate`, and
`io.katacontainers.config.hypervisor.tx_rate_limiter_max_rate`.

**Comment by bergwolf** [comment]
@Pennyzct docs for 2.0 has been moved to https://github.com/kata-containers/kata-containers/tree/2.0-dev/docs 
Please send related docs changes to `2.0-dev` branch of https://github.com/kata-containers/kata-containers as well.
