### ISSUE TITLE
Could the storage size be configured for Kata container?

### ISSUE THREAD

**Issue by lzha106** [kata-containers/documentation#687]
Seems the default storage size is 10G for Kata container:

```
root@f8f357923b79:/# df -lh
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda         10G  127M  9.9G   2% /
tmpfs            64M     0   64M   0% /dev
tmpfs           994M     0  994M   0% /sys/fs/cgroup
```

Wonder if it is configurable and where it is? I don't see any options in configuration.toml or Per-pod kata annotation.

**Comment by devimc** [comment]
could you add more details? I guess you're using devicemapper, so this is container engine specific (cri-o, docker, etc)

**Comment by lzha106** [comment]
> could you add more details? I guess you're using devicemapper, so this is container manager specific (cri-o, docker, etc)

thanks @devimc，I got it. 
Seems Kata VM works tranparently with docker volume. 
Yes, I used devicemapper as default and can control disk size by setting storage-opts.

**Comment by devimc** [comment]
@lzha106 thanks, can we close this?
