### ISSUE TITLE
Invalid picture url

### ISSUE THREAD

**Issue by LinshanYu** [kata-containers/documentation#689]
# Description of problem

There are a lot of broken pic links in this document, which affects my learning of kata, especially some pic which  describes the process or structure. I hope everyone can participate and add pictures.

**Comment by liubin** [comment]
Thanks @LinshanYu .

Can you post some examples of broken picture link? Or can you do a double check if it's broken links or network failures?

**Comment by LinshanYu** [comment]
> Thanks @LinshanYu .
> 
> Can you post some examples of broken picture link? Or can you do a double check if it's broken links or network failures?

There are many broken picture links in the document https://github.com/kata-containers/documentation/blob/master/design/architecture.md.    E.g https://github.com/kata-containers/documentation/blob/master/design/arch-images/docker-kata.png

**Comment by liubin** [comment]
Hi @LinshanYu , I have tested that the pictures are all ok.

I think you can try to use a proxy to access `https://raw.githubusercontent.com/`

**Comment by LinshanYu** [comment]
> Hi @LinshanYu , I have tested that the pictures are all ok.
> 
> I think you can try to use a proxy to access `https://raw.githubusercontent.com/`
ths

**Comment by jodh-intel** [comment]
ftr, we also run the following tool in our CI to ensure links don't break (either our links, or external URLs) :smile::

https://github.com/kata-containers/tests/tree/master/cmd/check-markdown
