### ISSUE TITLE
Need to update the prereqs for Kata Dev env setup

### ISSUE THREAD

**Issue by coolsvap** [kata-containers/documentation#7]
While trying to setup the Dev Environment for Kata I came across some dependencies (e.g make, gcc) which need to be installed before proceeding with the dev env setup. We can also incorporate links to relevant documents (e.g. Golang install steps)

**Comment by jodh-intel** [comment]
Hi @coolsvap - thanks for reporting. I've added `make` to the assumptions section in:

- https://github.com/kata-containers/documentation/wiki/Developer-Guide

Please feel free to update the doc further though as it's a wiki. BTW, here's the Clear Containers dev guide for comparison:

- https://github.com/clearcontainers/runtime/blob/master/docs/developers-clear-containers-install.md

**Comment by coolsvap** [comment]
sure @jodh-intel

**Comment by jodh-intel** [comment]
Thanks @coolsvap! ;)

**Comment by coolsvap** [comment]
@jodh-intel we also need to install gcc as part of dependencies prior to setting up the dev environment. I tried updating the wiki, but I do not have permission to update the doc.

**Comment by jodh-intel** [comment]
Hi @coolsvap - ok, I've updated https://github.com/kata-containers/documentation/wiki/Developer-Guide#assumptions based on your info. Is there anything else to add or shall we close this issue now?

**Comment by coolsvap** [comment]
Sure. I think we are good. Closing the issue

**Comment by jodh-intel** [comment]
Great - thanks for your contribution @coolsvap!
