### ISSUE TITLE
How to use another user to create a container when userns is opened

### ISSUE THREAD

**Issue by fansmit** [kata-containers/documentation#705]
I have 2 users on linux OS: user1(1000) and user2(1001)， and I've logged in with user1.
Now I want to create a new container with user2, then I input the command: 
`sudo docker run -it --user=1001 --name u1 ubuntu bash`
but I get the error: 
`docker: Error response from daemon: OCI runtime create failed: rpc error: code = Unknown desc = User namespaces enabled, but no user mapping found.: unknown.
ERRO[0001] error waiting for container: context canceled
`
the following are my user info:
`$ id
uid=1001(user2) gid=1001(user2) 组=1001(test),27(sudo),128(dockremap),999(docker)`

`
docker:x:999:dockremap,user2,root,user1
dockremap:x:128:user2,user1,root
user2:x:1001:dockremap

`
`
$ cat /etc/subuid
user1:100000:65536
dockremap:165536:65536
user2:231072:65536
`
`
$ cat /etc/subgid
user1:100000:65536
dockremap:165536:65536
user2:231072:65536
`
/etc/docker/daemon.json
`
{
"userns-remap": "default",
}
`
I tried restart dockerd without kata-runtime, the container can be created successfully.

so, how can I do for this problem?

**Comment by devimc** [comment]
I couldn't reproduce this,

```
$ sudo docker run -ti --rm --runtime kata-runtime --user=1001 ubuntu bash 
I have no name!@836033c7e31c:/$ exit

$ docker run -v /etc/passwd:/etc/passwd -ti --rm --runtime kata-runtime --user=1001 ubuntu bash 
user2@641ec5054229:/$
```

**Comment by fansmit** [comment]
> I couldn't reproduce this,
> 
> ```
> $ sudo docker run -ti --rm --runtime kata-runtime --user=1001 ubuntu bash 
> I have no name!@836033c7e31c:/$ exit
> 
> $ docker run -v /etc/passwd:/etc/passwd -ti --rm --runtime kata-runtime --user=1001 ubuntu bash 
> user2@641ec5054229:/$
> ```

You are right, I don't have to add the "userns-remap" in daemon.json. The container is directly created, that is ok.
Thank you very much!
