### ISSUE TITLE
Update Installation Guide to better reflect the current state of the project

### ISSUE THREAD

**Issue by fidencio** [kata-containers/documentation#708]
As per the discussion that happened in the Kata Architects Meeting that happend Today (Aug 25th 2020), we must document better what are the distributions we (as a community) provide the packages, what are the distributions packaging kata-containers themselves, and update the content pointing to kata-deploy.

This can be done in a few steps:
- [x] Update the list of the official distributions
  1. [x] Current content shows openSUSE Tumbleweed, but seems that it's also already packaged for SLE 15, openSUSE Leap 15.1, 15.2 (see: https://build.opensuse.org/package/show/devel:kubic/katacontainers)
  2. [x] Fedora 32 and onwards already have kata working out of the box
  3. [x] CentOS already have, via the Virtualization Special Interest Group, packages that mirror the Fedora ones: http://mirror.centos.org/centos/8/virt/x86_64/kata-containers/ (instructions on how to use must be added);
- [x] Update the list of provided by community packages (for 1.x)
  1. [x] CentOS 7 can be dropped;
  2. [x] Debian 9 is oldstable now, shall we keep supporting it? Does it work for Debian 10+?
  3. [x] Fedora 28, 29, and 30 are EOL.
  4. [x] openSUSE, seems we can stop distributing that as the distro already provides those
  5. [x] RHEL 7 can be dropped;
  6. [x] SLES 12 SP3, we need to check with someone from SUSE, but may be we should drop it considering they already have the official ones for SLE 15.
  7. [x] Ubuntu 16.04 has reached its EOL now and should be dropped. Does it work for 18.04 and 20.04?
- [x] Drop the packages provided by the community, in favour of kata-deploy (for 2.0)
- [ ] Document kata-deploy

**Comment by fidencio** [comment]
@rhafer, @saschagrunert, may I ask you for help to confirm the status on SLE / openSUSE?

**Comment by jodh-intel** [comment]
Related:

- https://github.com/kata-containers/kata-containers/issues/198
- https://github.com/kata-containers/packaging/issues/6
- https://github.com/kata-containers/packaging/wiki/Distro-packaging-status

**Comment by rhafer** [comment]
> @rhafer, @saschagrunert, may I ask you for help to confirm the status on SLE / openSUSE?

Sure. Basically your summary is correct. We maintain our packages in the above mentioned project (devel:kubic) in OBS. For Tumbleweed they're already part of the main distribution and for SLES and Leap it's a matter of add the respective repos of the above OBS project to install them.

The packaging however slightly differs to what is provided via the "home:katacontainers":
* We only have 2 packages: `katacontainers` which basically provides the runtime and configs and `katacontainers-image-initrd` which provide an kernel and initrd image suitable for kata and derived from our default kernel
* We rely on the qemu and kernel versions that ships with the distro, which means that we might lack certain features (e.g. virtio-fs is still tricky on SLES with that).

**Comment by fidencio** [comment]
> > @rhafer, @saschagrunert, may I ask you for help to confirm the status on SLE / openSUSE?
> 
> Sure. Basically your summary is correct. We maintain our packages in the above mentioned project (devel:kubic) in OBS. For Tumbleweed they're already part of the main distribution and for SLES and Leap it's a matter of add the respective repos of the above OBS project to install them.
> 
> The packaging however slightly differs to what is provided via the "home:katacontainers":

I'd say that's fine and that we should start relying more on the distro packages. If the users may want something different, they can either build their own or take advantage of the kata-deploy.

> 
> * We only have 2 packages: `katacontainers` which basically provides the runtime and configs and `katacontainers-image-initrd` which provide an kernel and initrd image suitable for kata and derived from our default kernel

Ack!

> * We rely on the qemu and kernel versions that ships with the distro, which means that we might lack certain features (e.g. virtio-fs is still tricky on SLES with that).

Yeah, we do something quite similar on Fedora / CentOS side, where we rely entirely on the distro's kernel & qemu, with the limitations of those two.

Soon enough I'll start updating the items I've proposed.

@rhafer, thanks a lot for the very quick reply!
