### ISSUE TITLE
How to use kata-container runtime with k8s cluster

### ISSUE THREAD

**Issue by ravvy00** [kata-containers/documentation#738]
**Which feature do you think can be improved?**

Specify the feature you think could be made better.

**How can it be improved?**

Describe how specifically you think it could be improved.

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by chavafg** [comment]
Hi @ravvy00, here is a guide that can help you: https://github.com/kata-containers/documentation/tree/master/how-to#kubernetes-integration 

Let us know if you have any question.

**Comment by ariel-adam** [comment]
Closing this issue since Salvador provided an answer.
