### ISSUE TITLE
the documentation has more error url

### ISSUE THREAD

**Issue by timyinshi** [kata-containers/documentation#740]
# Description of problem
the documentation has more error url:
https://docs.fluentbit.io/manual/parser/logfmt
https://projectacrn.github.io/latest/tutorials/kbl-nuc-sdc.html
https://github.com/davidhildenbrand/qemu/tree/virtio-mem
https://istio.io/docs/setup/kubernetes/quick-start/
https://raw.githubusercontent.com/kata-containers/documentation/master/install/docker/
https://raw.githubusercontent.com/kata-containers/documentation/master/install/

# Expected result
use the right url

**Comment by CriaHu** [comment]
2 3 4

**Comment by gaoguangze111** [comment]
12 the last one

**Comment by CriaHu** [comment]
@timyinshi All links with "https://www.googleapis.com/"  are not 404.It's just that you don't have authority.
```
https://www.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx

{
"error": {
"code": 401,
"message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
"errors": [
{
"message": "Login Required.",
"domain": "global",
"reason": "required",
"location": "Authorization",
"locationType": "header"
}
],
"status": "UNAUTHENTICATED"
}
}
```

**Comment by timyinshi** [comment]
@CriaHu  ok

**Comment by jodh-intel** [comment]
We do currently filter out googleapis URLs in the static checker here:

- https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L730..L731
