### ISSUE TITLE
fail to start kata with firecracker 

### ISSUE THREAD

**Issue by magnate3** [kata-containers/documentation#749]
kernel_path="/usr/share/kata-containers/vmlinux.container"
rootfs_path="/usr/share/kata-containers/kata-containers.img"
curl --unix-socket /tmp/firecracker.socket -i \
       -X PUT 'http://localhost/boot-source'   \
       -H 'Accept: application/json'           \
       -H 'Content-Type: application/json'     \
       -d "{
             \"kernel_image_path\": \"${kernel_path}\",
             \"boot_args\": \"keep_bootcon console=ttyS0 reboot=k panic=1 pci=off\"
        }"
 

curl --unix-socket /tmp/firecracker.socket -i \
   -X PUT 'http://localhost/drives/rootfs' \
   -H 'Accept: application/json'           \
   -H 'Content-Type: application/json'     \
   -d "{
         \"drive_id\": \"rootfs\",
         \"path_on_host\": \"${rootfs_path}\",
         \"is_root_device\": true,
         \"is_read_only\": false
    }"
curl --unix-socket /tmp/firecracker.socket -i \
   -X PUT 'http://localhost/actions'       \
   -H  'Accept: application/json'          \
   -H  'Content-Type: application/json'    \
   -d '{
       "action_type": "InstanceStart"
    }'
[root@bogon ~]# firecracker --api-sock /tmp/firecracker.socket
2020-10-19T18:52:55.140685005 [anonymous-instance:ERROR:src/api_server/src/parsed_request.rs:95] Received Error. Status code: 400 Bad Request. Message: Cannot load kernel due to invalid memory configuration or invalid kernel image. Invalid ELF magic number

**Comment by jodh-intel** [comment]
Hi @magnate3 - thanks for raising. However, please can you add in the information requested in the template? Specifically this:

# Get your issue reviewed faster

To help us understand the problem more quickly, please do the following:

1. Run the `kata-collect-data.sh` script, which is installed as part of Kata Containers.
   ```sh
   $ sudo kata-collect-data.sh > /tmp/kata.log
   ```
1. Review the output file (`/tmp/kata.log`) to ensure it doesn't
   contain any private / sensitive information
1. Paste the *entire* contents of the file into this issue as a comment
   (the script generates markdown format output).

The information provided will help us to understand the problem more quickly
so saves time for both of us! :smile:

**Comment by jodh-intel** [comment]
Closing since the user has raised another issue for the same problem at https://github.com/kata-containers/kata-containers/issues/999.
