### ISSUE TITLE
How to run kata gpu containers with k8s cluster

### ISSUE THREAD

**Issue by lizhixin3016** [kata-containers/documentation#764]
To run gpu containers with kata-runtime, we need to enable vfio driver for gpu devices,
but the k8s-device-plugin need to install nvidia driver on k8s node to detect the gpu
devices, causing we can not passthrough gpu devices by vfio-pci driver into the kata
containers.

I didn't find any introduction or document about this, anyone knows how to deal with it?

**Comment by Jimmy-Xu** [comment]
@lizhixin3016 
Have you tried this device plugin https://github.com/NVIDIA/kubevirt-gpu-device-plugin? 
It does not need to install nvidia driver on k8s node,  and you can passthrough the VFIO device of Nvidia to the kata container.
You can install and load the Nvidia driver into the guest kernel rootfs image or kata container.

**Comment by lizhixin3016** [comment]
@Jimmy-Xu
This plugin looks useful to me, I will try deploy and run it with kata in k8s cluster.

Thank you very much!

**Comment by liubin** [comment]
@lizhixin3016 , if Jimmy's comment helped you, consider closing this issue?

**Comment by ariel-adam** [comment]
Closing this issue.
