### ISSUE TITLE
how to run kata in a runing kubernetes cluster

### ISSUE THREAD

**Issue by wanghonglei5181** [kata-containers/documentation#771]
in the kata doc ,i found how to run kata in a new cluster, but i can't find the doc that in a running cluster.
i can't run the command in the doc like the below. a lot of online pods running in my cluster.
$ sudo kubeadm init --skip-preflight-checks --cri-socket /run/containerd/containerd.sock --pod-network-cidr=10.244.0.0/16"

version
kubernetes: 1.17.3
docker:19.03
os: centos7

**Comment by wanghonglei5181** [comment]
1,install cro-o and kata container on a kubenetes node
2,use kubeadm join
3,create runtimeClass
4,spec:
  runtimeClassName: katav2
  containers:
  - name: nginx
    image: nginx
it works !!

**Comment by ariel-adam** [comment]
Closing this issue.
