### ISSUE TITLE
Convert install docs to use bash code blocks for commands

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/documentation#92]
We have a crazy idea (#91) which will allow our documentation to be "executed" by users (and by our CI systems. That ensures the docs are always correct. We need to modify the install docs to "flag" those code blocks that are executable by changing the basic code blocks:

```
    ```
    stuff
    ```
```

into a bash code block:

```
    ```bash
    bash commands!
    ```
```

**Comment by egernst** [comment]
@bergwolf @gnawux  - PTAL.  James has gone off the deep end :)

**Comment by jodh-intel** [comment]
哈哈 :smile:

We'll obviously have to be careful where we run the scripts we generate, but we can sanity check the install docs and also use the script "in anger" for https://github.com/kata-containers/osbuilder/issues/97 for example.
